time="2025-10-30T23:58:09+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2024-7314/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 745B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 209B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.11-slim
#3 DONE 1.1s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 649B done
#5 DONE 0.0s

#6 [1/5] FROM docker.io/library/python:3.11-slim@sha256:8eb5fc663972b871c528fef04be4eaa9ab8ab4539a5316c4b8c133771214a617
#6 resolve docker.io/library/python:3.11-slim@sha256:8eb5fc663972b871c528fef04be4eaa9ab8ab4539a5316c4b8c133771214a617 0.0s done
#6 CACHED

#7 [2/5] WORKDIR /usr/src/app
#7 DONE 0.0s

#8 [3/5] COPY requirements.txt ./
#8 DONE 0.0s

#9 [4/5] RUN pip install --no-cache-dir -r requirements.txt
#9 2.214 Collecting Flask==2.0.0 (from -r requirements.txt (line 1))
#9 2.392   Downloading Flask-2.0.0-py3-none-any.whl.metadata (3.8 kB)
#9 2.445 Collecting Werkzeug>=2.0 (from Flask==2.0.0->-r requirements.txt (line 1))
#9 2.464   Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
#9 2.504 Collecting Jinja2>=3.0 (from Flask==2.0.0->-r requirements.txt (line 1))
#9 2.523   Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
#9 2.888 Collecting itsdangerous>=2.0 (from Flask==2.0.0->-r requirements.txt (line 1))
#9 2.907   Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
#9 2.975 Collecting click>=7.1.2 (from Flask==2.0.0->-r requirements.txt (line 1))
#9 2.994   Downloading click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
#9 3.111 Collecting MarkupSafe>=2.0 (from Jinja2>=3.0->Flask==2.0.0->-r requirements.txt (line 1))
#9 3.132   Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
#9 3.161 Downloading Flask-2.0.0-py3-none-any.whl (93 kB)
#9 3.185    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 4.1 MB/s eta 0:00:00
#9 3.205 Downloading click-8.3.0-py3-none-any.whl (107 kB)
#9 3.213    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 kB 21.8 MB/s eta 0:00:00
#9 3.232 Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 3.252 Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
#9 3.268    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 9.4 MB/s eta 0:00:00
#9 3.284 Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
#9 3.308    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 9.9 MB/s eta 0:00:00
#9 3.326 Downloading markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
#9 3.376 Installing collected packages: MarkupSafe, itsdangerous, click, Werkzeug, Jinja2, Flask
#9 3.677 Successfully installed Flask-2.0.0 Jinja2-3.1.6 MarkupSafe-3.0.3 Werkzeug-3.1.3 click-8.3.0 itsdangerous-2.2.0
#9 3.677 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 3.789 
#9 3.789 [notice] A new release of pip is available: 24.0 -> 25.3
#9 3.789 [notice] To update, run: pip install --upgrade pip
#9 DONE 3.9s

#10 [5/5] COPY app.py ./
#10 DONE 0.0s

#11 exporting to image
#11 exporting layers
#11 exporting layers 0.6s done
#11 exporting manifest sha256:e02e4b7f84ad6c672cce1e078ccc9db781eb149a97ef52b8ca70d91d7c765108 0.0s done
#11 exporting config sha256:b66e465e44ea43d5c7cf61c0b3611e8586992fab9f99fdb16bb59e3c59d9f214 0.0s done
#11 exporting attestation manifest sha256:375ca01be23e14cdd0095733b4489ddd60485ecd8436dbd351617a6efb261fe0 0.0s done
#11 exporting manifest list sha256:10fa8e1d413937517efd3af7c874b1d43be3b70969d93007d0c6c9c8b0bac970 0.0s done
#11 naming to docker.io/library/custom_no_tool-vulnerable-app:latest done
#11 unpacking to docker.io/library/custom_no_tool-vulnerable-app:latest
#11 unpacking to docker.io/library/custom_no_tool-vulnerable-app:latest 0.3s done
#11 DONE 1.0s

#12 resolving provenance for metadata file
#12 DONE 0.0s
 custom_no_tool-vulnerable-app  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container custom_no_tool-vulnerable-app-1  Creating
 Container custom_no_tool-vulnerable-app-1  Created
 Container custom_no_tool-vulnerable-app-1  Starting
 Container custom_no_tool-vulnerable-app-1  Started


sudo docker logs 72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/usr/src/app/app.py", line 2, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 14, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)




sudo docker inspect 72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746[
    {
        "Id": "72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746",
        "Created": "2025-10-30T22:58:16.229970154Z",
        "Path": "python",
        "Args": [
            "app.py"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-30T22:58:45.568600685Z",
            "FinishedAt": "2025-10-30T22:58:46.11371699Z"
        },
        "Image": "sha256:10fa8e1d413937517efd3af7c874b1d43be3b70969d93007d0c6c9c8b0bac970",
        "ResolvConfPath": "/var/lib/docker/containers/72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746/hostname",
        "HostsPath": "/var/lib/docker/containers/72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746/hosts",
        "LogPath": "/var/lib/docker/containers/72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746/72f74f087473d1af5b1d9a52e8ef272bed4b88e4ad94bcb3e596a03a8070e746-json.log",
        "Name": "/custom_no_tool-vulnerable-app-1",
        "RestartCount": 9,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "5000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "72f74f087473",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "FLASK_ENV=development",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
                "PYTHON_VERSION=3.11.14",
                "PYTHON_SHA256=8d3ed8ec5c88c1c95f5e558612a725450d2452813ddad5e58fdb1a53b1209b78"
            ],
            "Cmd": [
                "python",
                "app.py"
            ],
            "Image": "custom_no_tool-vulnerable-app",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "c9876601b8f607aff45a7c426af79b4e4c6f6d9fb69dbe8e29707ea54229387f",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:10fa8e1d413937517efd3af7c874b1d43be3b70969d93007d0c6c9c8b0bac970",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2024-7314/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2024-7314/custom_no_tool",
                "com.docker.compose.service": "vulnerable-app",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-vulnerable-app-1",
                        "vulnerable-app"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "ff6a9190fa065cc49cf7b78740c7e11738afef252974b19147b56a124cc20877",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-vulnerable-app-1",
                        "vulnerable-app",
                        "72f74f087473"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:e02e4b7f84ad6c672cce1e078ccc9db781eb149a97ef52b8ca70d91d7c765108",
            "size": 1811,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]