{
  "version": "15.0.6",
  "vulnerabilities": [
    {
      "id": "981d544affbb95d265d23199c97965ba90bed20307302da2abfb57e60531f804",
      "category": "container_scanning",
      "message": "CVE-2014-1624 on pyxdg@0.25",
      "description": "Race condition in the `xdg.BaseDirectory.get_runtime_dir` function in pyxdg 0.25 allows local users to overwrite arbitrary files by pre-creating `/tmp/pyxdg-runtime-dir-fallback-victim` to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the `get_runtime_dir` function is called.",
      "cve": "CVE-2014-1624",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade pyxdg@0.25 to 0.26",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyxdg@0.25"
          },
          "version": "0.25"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2014-1624",
          "value": "CVE-2014-1624",
          "url": "https://scout.docker.com/v/CVE-2014-1624?s=github&n=pyxdg&t=pypi&vr=%3C%3D0.25"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2014-1624?s=github&n=pyxdg&t=pypi&vr=%3C%3D0.25"
        }
      ]
    },
    {
      "id": "3051b3b0e4b0df0a51e58046da99c0ba3f3bc42b214ff3715ed0e70bb6f1a9a5",
      "category": "container_scanning",
      "message": "CVE-2024-39689 on certifi@2021.10.8",
      "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
      "cve": "CVE-2024-39689",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade certifi@2021.10.8 to 2024.7.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/certifi@2021.10.8"
          },
          "version": "2021.10.8"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-39689",
          "value": "CVE-2024-39689",
          "url": "https://scout.docker.com/v/CVE-2024-39689?s=github&n=certifi&t=pypi&vr=%3E%3D2021.5.30%2C%3C2024.7.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-39689?s=github&n=certifi&t=pypi&vr=%3E%3D2021.5.30%2C%3C2024.7.4"
        }
      ]
    },
    {
      "id": "615140d496c890201d592d4cff486839c93fd150079f64e7f0a71640a26a22ea",
      "category": "container_scanning",
      "message": "GHSA-5cpq-8wj7-hf2v on cryptography@2.1.4",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "GHSA-5cpq-8wj7-hf2v",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 41.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-5cpq-8wj7-hf2v",
          "value": "GHSA-5cpq-8wj7-hf2v",
          "url": "https://scout.docker.com/v/GHSA-5cpq-8wj7-hf2v?s=github&n=cryptography&t=pypi&vr=%3E%3D0.5%2C%3C%3D40.0.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-5cpq-8wj7-hf2v?s=github&n=cryptography&t=pypi&vr=%3E%3D0.5%2C%3C%3D40.0.2"
        }
      ]
    },
    {
      "id": "1bf31ca4130401ae2fb8a8736cbe485b0c9ebd49930c7d57df36bd25cff3c00b",
      "category": "container_scanning",
      "message": "GHSA-jm77-qphf-c4w8 on cryptography@2.1.4",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8-41.0.2 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230731.txt, https://www.openssl.org/news/secadv/20230719.txt, and https://www.openssl.org/news/secadv/20230714.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "GHSA-jm77-qphf-c4w8",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 41.0.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-jm77-qphf-c4w8",
          "value": "GHSA-jm77-qphf-c4w8",
          "url": "https://scout.docker.com/v/GHSA-jm77-qphf-c4w8?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8%2C%3C41.0.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-jm77-qphf-c4w8?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8%2C%3C41.0.3"
        }
      ]
    },
    {
      "id": "18124f1eff81d0aa73f0959398801b40373f4703828915df3c88eb74d366a067",
      "category": "container_scanning",
      "message": "CVE-2022-22935 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. A minion authentication denial of service can cause a MiTM attacker to force a minion process to stop by impersonating a master.",
      "cve": "CVE-2022-22935",
      "severity": "Low",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22935",
          "value": "CVE-2022-22935",
          "url": "https://scout.docker.com/v/CVE-2022-22935?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22935?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "d9fd93fe9225ebd0cf41c8caa22cb486f9542f4b620c4cbe7d1175a897875819",
      "category": "container_scanning",
      "message": "GHSA-qppv-j76h-2rpx on tornado@5.1.1",
      "description": "## Summary\nTornado interprets `-`, `+`, and `_` in chunk length and `Content-Length` values, which are not allowed by the HTTP RFCs. This can result in request smuggling when Tornado is deployed behind certain proxies that interpret those non-standard characters differently. This is known to apply to older versions of haproxy, although the current release is not affected.\n\n## Details\nTornado uses the `int` constructor to parse the values of `Content-Length` headers and chunk lengths in the following locations:\n### `tornado/http1connection.py:445`\n```python3\n            self._expected_content_remaining = int(headers[\"Content-Length\"])\n```\n### `tornado/http1connection.py:621`\n```python3\n                content_length = int(headers[\"Content-Length\"])  # type: Optional[int]\n```\n### `tornado/http1connection.py:671`\n```python3\n            chunk_len = int(chunk_len_str.strip(), 16)\n```\nBecause `int(\"0_0\") == int(\"+0\") == int(\"-0\") == int(\"0\")`, using the `int` constructor to parse and validate strings that should contain only ASCII digits is not a good strategy. \n\n",
      "cve": "GHSA-qppv-j76h-2rpx",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.3.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-qppv-j76h-2rpx",
          "value": "GHSA-qppv-j76h-2rpx",
          "url": "https://scout.docker.com/v/GHSA-qppv-j76h-2rpx?s=github&n=tornado&t=pypi&vr=%3C6.3.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-qppv-j76h-2rpx?s=github&n=tornado&t=pypi&vr=%3C6.3.3"
        }
      ]
    },
    {
      "id": "31c944eae8103293556a16a0e2b7078db6ec3bac1833cb1d38c093435cbfdf47",
      "category": "container_scanning",
      "message": "CVE-2023-20898 on salt@2019.2.3",
      "description": "Git Providers can read from the wrong environment because they get the same cache directory base name in Salt masters prior to 3005.2 or 3006.2. Anything that uses Git Providers with different environments can get garbage data or the wrong data, which can lead to wrongful data disclosure, wrongful executions, data corruption and/or crash.",
      "cve": "CVE-2023-20898",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3005.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-20898",
          "value": "CVE-2023-20898",
          "url": "https://scout.docker.com/v/CVE-2023-20898?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-20898?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ]
    },
    {
      "id": "b7228816b98cfa8856b6c912468434c67a1daa7f30cc380f9de8428206498dea",
      "category": "container_scanning",
      "message": "CVE-2021-25284 on salt@2019.2.3",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. `salt.modules.cmdmod` can log credentials to the info or error log level.",
      "cve": "CVE-2021-25284",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25284",
          "value": "CVE-2021-25284",
          "url": "https://scout.docker.com/v/CVE-2021-25284?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25284?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "2b1377fac277cf569eff13b89d33d7731d443d49c38423e2bb8f278460b75b1d",
      "category": "container_scanning",
      "message": "CVE-2024-22231 on salt@2019.2.3",
      "description": "Syndic cache directory creation is vulnerable to a directory traversal attack in salt project which can lead a malicious attacker to create an arbitrary directory on a Salt master.",
      "cve": "CVE-2024-22231",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3005.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22231",
          "value": "CVE-2024-22231",
          "url": "https://scout.docker.com/v/CVE-2024-22231?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22231?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ]
    },
    {
      "id": "211275980ab15f3dd1f7cd60d1ccb0c13d872720a501c2abdb732fc1b4864201",
      "category": "container_scanning",
      "message": "CVE-2023-20897 on salt@2019.2.3",
      "description": "Salt masters prior to 3005.2 or 3006.2 contain a DOS in minion return. After receiving several bad packets on the request server equal to the number of worker threads, the master will become unresponsive to return requests until restarted.",
      "cve": "CVE-2023-20897",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3005.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-20897",
          "value": "CVE-2023-20897",
          "url": "https://scout.docker.com/v/CVE-2023-20897?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-20897?s=github&n=salt&t=pypi&vr=%3C3005.2"
        }
      ]
    },
    {
      "id": "1d892ef9c9cfb0895865e7c46fbf6211848f2356f3c4380dc77965a4f0aa6cdf",
      "category": "container_scanning",
      "message": "CVE-2023-28370 on tornado@5.1.1",
      "description": "Open redirect vulnerability in Tornado versions 6.3.1 and earlier allows a remote unauthenticated attacker to redirect a user to an arbitrary web site and conduct a phishing attack by having user access a specially crafted URL.",
      "cve": "CVE-2023-28370",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.3.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-28370",
          "value": "CVE-2023-28370",
          "url": "https://scout.docker.com/v/CVE-2023-28370?s=github&n=tornado&t=pypi&vr=%3C6.3.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-28370?s=github&n=tornado&t=pypi&vr=%3C6.3.2"
        }
      ]
    },
    {
      "id": "2e39adf172abf39f2f13f2e3140425ce3c9933644b765d77413ef272778dd7db",
      "category": "container_scanning",
      "message": "CVE-2024-47081 on requests@2.27.1",
      "description": "### Impact\n\nDue to a URL parsing issue, Requests releases prior to 2.32.4 may leak .netrc credentials to third parties for specific maliciously-crafted URLs.\n\n### Workarounds\nFor older versions of Requests, use of the .netrc file can be disabled with `trust_env=False` on your Requests Session ([docs](https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env)).\n\n### References\nhttps://github.com/psf/requests/pull/6965\nhttps://seclists.org/fulldisclosure/2025/Jun/2",
      "cve": "CVE-2024-47081",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.27.1 to 2.32.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.27.1"
          },
          "version": "2.27.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-47081",
          "value": "CVE-2024-47081",
          "url": "https://scout.docker.com/v/CVE-2024-47081?s=github&n=requests&t=pypi&vr=%3C2.32.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-47081?s=github&n=requests&t=pypi&vr=%3C2.32.4"
        }
      ]
    },
    {
      "id": "0f96078d5b49193bb4db45b60c2c85a6f5e59636b0ec7a31f1ce4f4ffa43ec49",
      "category": "container_scanning",
      "message": "CVE-2025-50181 on urllib3@1.26.20",
      "description": "urllib3 handles redirects and retries using the same mechanism, which is controlled by the `Retry` object. The most common way to disable redirects is at the request level, as follows:\n\n```python\nresp = urllib3.request(\"GET\", \"https://httpbin.org/redirect/1\", redirect=False)\nprint(resp.status)\n# 302\n```\n\nHowever, it is also possible to disable redirects, for all requests, by instantiating a `PoolManager` and specifying `retries` in a way that disable redirects:\n\n```python\nimport urllib3\n\nhttp = urllib3.PoolManager(retries=0)  # should raise MaxRetryError on redirect\nhttp = urllib3.PoolManager(retries=urllib3.Retry(redirect=0))  # equivalent to the above\nhttp = urllib3.PoolManager(retries=False)  # should return the first response\n\nresp = http.request(\"GET\", \"https://httpbin.org/redirect/1\")\n```\n\nHowever, the `retries` parameter is currently ignored, which means all the above examples don't disable redirects.\n\n## Affected usages\n\nPassing `retries` on `PoolManager` instantiation to disable redirects or restrict their number.\n\nBy default, requests and botocore users are not affected.\n\n## Impact\n\nRedirects are often used to exploit SSRF vulnerabilities. An application attempting to mitigate SSRF or open redirect vulnerabilities by disabling redirects at the PoolManager level will remain vulnerable.\n\n## Remediation\n\nYou can remediate this vulnerability with the following steps:\n\n * Upgrade to a patched version of urllib3. If your organization would benefit from the continued support of urllib3 1.x, please contact [sethmichaellarson@gmail.com](mailto:sethmichaellarson@gmail.com) to discuss sponsorship or contribution opportunities.\n * Disable redirects at the `request()` level instead of the `PoolManager()` level.",
      "cve": "CVE-2025-50181",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade urllib3@1.26.20 to 2.5.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/urllib3@1.26.20"
          },
          "version": "1.26.20"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-50181",
          "value": "CVE-2025-50181",
          "url": "https://scout.docker.com/v/CVE-2025-50181?s=github&n=urllib3&t=pypi&vr=%3C2.5.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-50181?s=github&n=urllib3&t=pypi&vr=%3C2.5.0"
        }
      ]
    },
    {
      "id": "90c2f49e8f7c26b6194c657736bd12225018a706d468b0add39fdb3370fb9d24",
      "category": "container_scanning",
      "message": "GHSA-753j-mpmx-qq6g on tornado@5.1.1",
      "description": "### Summary\nWhen Tornado receives a request with two `Transfer-Encoding: chunked` headers, it ignores them both. This enables request smuggling when Tornado is deployed behind a proxy server that emits such requests. [Pound](https://en.wikipedia.org/wiki/Pound_(networking)) does this.\n\n### PoC\n0. Install Tornado.\n1. Start a simple Tornado server that echoes each received request's body:\n```bash\ncat << EOF > server.py\nimport asyncio\nimport tornado\n\nclass MainHandler(tornado.web.RequestHandler):\n    def post(self):\n        self.write(self.request.body)\n\nasync def main():\n    tornado.web.Application([(r\"/\", MainHandler)]).listen(8000)\n    await asyncio.Event().wait()\n\nasyncio.run(main())\nEOF\npython3 server.py &\n```\n2. Send a valid chunked request:\n```bash\nprintf 'POST / HTTP/1.1\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n1\\r\\nZ\\r\\n0\\r\\n\\r\\n' | nc localhost 8000\n```\n3. Observe that the response is as expected:\n```\nHTTP/1.1 200 OK\nServer: TornadoServer/6.3.3\nContent-Type: text/html; charset=UTF-8\nDate: Sat, 07 Oct 2023 17:32:05 GMT\nContent-Length: 1\n\nZ\n```\n4. Send a request with two `Transfer-Encoding: chunked` headers:\n```\nprintf 'POST / HTTP/1.1\\r\\nTransfer-Encoding: chunked\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n1\\r\\nZ\\r\\n0\\r\\n\\r\\n' | nc localhost 8000\n```\n5. Observe the strange response:\n```\nHTTP/1.1 200 OK\nServer: TornadoServer/6.3.3\nContent-Type: text/html; charset=UTF-8\nDate: Sat, 07 Oct 2023 17:35:40 GMT\nContent-Length: 0\n\nHTTP/1.1 400 Bad Request\n\n```\nThis is because Tornado believes that the request has no message body, so it tries to interpret `1\\r\\nZ\\r\\n0\\r\\n\\r\\n` as its own request, which causes a 400 response. With a little cleverness involving `chunk-ext`s, you can get Tornado to instead respond 405, which has the potential to desynchronize the connection, as opposed to 400 which should always result in a connection closure.\n\n### Impact\nAnyone using Tornado behind a proxy that forwards requests containing multiple `Transfer-Encoding: chunked` headers is vulnerable to request smuggling, which may entail ACL bypass, cache poisoning, or connection desynchronization.\n",
      "cve": "GHSA-753j-mpmx-qq6g",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.4.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-753j-mpmx-qq6g",
          "value": "GHSA-753j-mpmx-qq6g",
          "url": "https://scout.docker.com/v/GHSA-753j-mpmx-qq6g?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-753j-mpmx-qq6g?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ]
    },
    {
      "id": "674c760e99de2c7ed409d9c13555a12a6ce7b04060f2069e08f363b1f3a4df1a",
      "category": "container_scanning",
      "message": "CVE-2024-22195 on jinja2@2.11.3",
      "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing spaces. XML/HTML attributes cannot contain spaces, as each would then be interpreted as a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. Note that accepting keys as user input is not common or a particularly intended use case of the `xmlattr` filter, and an application doing so should already be verifying what keys are provided regardless of this fix.",
      "cve": "CVE-2024-22195",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.11.3 to 3.1.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.11.3"
          },
          "version": "2.11.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22195",
          "value": "CVE-2024-22195",
          "url": "https://scout.docker.com/v/CVE-2024-22195?s=github&n=jinja2&t=pypi&vr=%3C3.1.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22195?s=github&n=jinja2&t=pypi&vr=%3C3.1.3"
        }
      ]
    },
    {
      "id": "0c6664c83858b63af77f36536238f96b67454a8088f3060c0c8a1d2943b1e09c",
      "category": "container_scanning",
      "message": "CVE-2024-34064 on jinja2@2.11.3",
      "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.",
      "cve": "CVE-2024-34064",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.11.3 to 3.1.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.11.3"
          },
          "version": "2.11.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-34064",
          "value": "CVE-2024-34064",
          "url": "https://scout.docker.com/v/CVE-2024-34064?s=github&n=jinja2&t=pypi&vr=%3C3.1.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-34064?s=github&n=jinja2&t=pypi&vr=%3C3.1.4"
        }
      ]
    },
    {
      "id": "052b04a5072bd4c51c50b23370fb411e86872056f7f233a01d4066cefe4ec168",
      "category": "container_scanning",
      "message": "CVE-2024-56326 on jinja2@2.11.3",
      "description": "An oversight in how the Jinja sandboxed environment detects calls to `str.format` allows an attacker that controls the content of a template to execute arbitrary Python code.\n\nTo exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates.\n\nJinja's sandbox does catch calls to `str.format` and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's `format` method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox.",
      "cve": "CVE-2024-56326",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.11.3 to 3.1.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.11.3"
          },
          "version": "2.11.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-56326",
          "value": "CVE-2024-56326",
          "url": "https://scout.docker.com/v/CVE-2024-56326?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-56326?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.4"
        }
      ]
    },
    {
      "id": "e9d010ef316f444029527b7aeb499e868c9030af9ba758ce8ebf07adc68ac8be",
      "category": "container_scanning",
      "message": "CVE-2025-27516 on jinja2@2.11.3",
      "description": "An oversight in how the Jinja sandboxed environment interacts with the `|attr` filter allows an attacker that controls the content of a template to execute arbitrary Python code.\n\nTo exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates.\n\nJinja's sandbox does catch calls to `str.format` and ensures they don't escape the sandbox. However, it's possible to use the `|attr` filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the `|attr` filter no longer bypasses the environment's attribute lookup.",
      "cve": "CVE-2025-27516",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade jinja2@2.11.3 to 3.1.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/jinja2@2.11.3"
          },
          "version": "2.11.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-27516",
          "value": "CVE-2025-27516",
          "url": "https://scout.docker.com/v/CVE-2025-27516?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-27516?s=github&n=jinja2&t=pypi&vr=%3C%3D3.1.5"
        }
      ]
    },
    {
      "id": "6600a0938dc7ed86851524e52e77572af35a6e34ebd718f9db75f3970cbacfc3",
      "category": "container_scanning",
      "message": "CVE-2020-17490 on salt@2019.2.3",
      "description": "The TLS module within SaltStack Salt through 3002 creates certificates with weak file permissions.",
      "cve": "CVE-2020-17490",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-17490",
          "value": "CVE-2020-17490",
          "url": "https://scout.docker.com/v/CVE-2020-17490?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-17490?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ]
    },
    {
      "id": "3b1b86c7a2e64196859f59e060b8d7c1d64c609484b4113074ecd2ebf660918a",
      "category": "container_scanning",
      "message": "CVE-2024-0727 on cryptography@2.1.4",
      "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
      "cve": "CVE-2024-0727",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 42.0.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-0727",
          "value": "CVE-2024-0727",
          "url": "https://scout.docker.com/v/CVE-2024-0727?s=github&n=cryptography&t=pypi&vr=%3C42.0.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-0727?s=github&n=cryptography&t=pypi&vr=%3C42.0.2"
        }
      ]
    },
    {
      "id": "d6269a904c7077a018e74e6aeff8e0939274e8fc4f624ce0a0aee23f29f0f952",
      "category": "container_scanning",
      "message": "CVE-2024-35195 on requests@2.27.1",
      "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
      "cve": "CVE-2024-35195",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.27.1 to 2.32.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.27.1"
          },
          "version": "2.27.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-35195",
          "value": "CVE-2024-35195",
          "url": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0"
        }
      ]
    },
    {
      "id": "04ccb62d67de91629091ded4388b993419be09d54aa635e835e654f15d6c4c59",
      "category": "container_scanning",
      "message": "CVE-2022-23491 on certifi@2021.10.8",
      "description": "Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nTrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ).",
      "cve": "CVE-2022-23491",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade certifi@2021.10.8 to 2022.12.07",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/certifi@2021.10.8"
          },
          "version": "2021.10.8"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-23491",
          "value": "CVE-2022-23491",
          "url": "https://scout.docker.com/v/CVE-2022-23491?s=github&n=certifi&t=pypi&vr=%3E%3D2017.11.05%2C%3C2022.12.07"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-23491?s=github&n=certifi&t=pypi&vr=%3E%3D2017.11.05%2C%3C2022.12.07"
        }
      ]
    },
    {
      "id": "1ca914469c3deb5d44c68cc62172bf624d5daa478406156ffb60d613830cd92c",
      "category": "container_scanning",
      "message": "CVE-2023-32681 on requests@2.27.1",
      "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
      "cve": "CVE-2023-32681",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade requests@2.27.1 to 2.31.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/requests@2.27.1"
          },
          "version": "2.27.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-32681",
          "value": "CVE-2023-32681",
          "url": "https://scout.docker.com/v/CVE-2023-32681?s=github&n=requests&t=pypi&vr=%3E%3D2.3.0%2C%3C2.31.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-32681?s=github&n=requests&t=pypi&vr=%3E%3D2.3.0%2C%3C2.31.0"
        }
      ]
    },
    {
      "id": "f51f0db1e4f9c864e03d360e1e9c0b9226c7ca384db81b7f96af3f3c5217ebdd",
      "category": "container_scanning",
      "message": "GHSA-w235-7p84-xx57 on tornado@5.1.1",
      "description": "### Summary\nTornado’s `curl_httpclient.CurlAsyncHTTPClient` class is vulnerable to CRLF (carriage return/line feed) injection in the request headers.\n\n### Details\nWhen an HTTP request is sent using `CurlAsyncHTTPClient`, Tornado does not reject carriage return (\\r) or line feed (\\n) characters in the request headers. As a result, if an application includes an attacker-controlled header value in a request sent using `CurlAsyncHTTPClient`, the attacker can inject arbitrary headers into the request or cause the application to send arbitrary requests to the specified server.\n\nThis behavior differs from that of the standard `AsyncHTTPClient` class, which does reject CRLF characters.\n\nThis issue appears to stem from libcurl's (as well as pycurl's) lack of validation for the [`HTTPHEADER`](https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html) option. libcurl’s documentation states:\n\n> The headers included in the linked list must not be CRLF-terminated, because libcurl adds CRLF after each header item itself. Failure to comply with this might result in strange behavior. libcurl passes on the verbatim strings you give it, without any filter or other safe guards. That includes white space and control characters.\n\npycurl similarly appears to assume that the headers adhere to the correct format. Therefore, without any validation on Tornado’s part, header names and values are included verbatim in the request sent by `CurlAsyncHTTPClient`, including any control characters that have special meaning in HTTP semantics.\n\n### PoC\nThe issue can be reproduced using the following script:\n\n```python\nimport asyncio\n\nfrom tornado import httpclient\nfrom tornado import curl_httpclient\n\nasync def main():\n    http_client = curl_httpclient.CurlAsyncHTTPClient()\n\n    request = httpclient.HTTPRequest(\n        # Burp Collaborator payload\n        \"http://727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com/\",\n        method=\"POST\",\n        body=\"body\",\n        # Injected header using CRLF characters\n        headers={\"Foo\": \"Bar\\r\\nHeader: Injected\"}\n    )\n\n    response = await http_client.fetch(request)\n    print(response.body)\n\n    http_client.close()\n\nif __name__ == \"__main__\":\n    asyncio.run(main())\n```\n\nWhen the specified server receives the request, it contains the injected header (`Header: Injected`) on its own line:\n\n```http\nPOST / HTTP/1.1\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com\nUser-Agent: Mozilla/5.0 (compatible; pycurl)\nAccept: */*\nAccept-Encoding: gzip,deflate\nFoo: Bar\nHeader: Injected\nContent-Length: 4\nContent-Type: application/x-www-form-urlencoded\n\nbody\n```\n\nThe attacker can also construct entirely new requests using a payload with multiple CRLF sequences. For example, specifying a header value of `\\r\\n\\r\\nPOST /attacker-controlled-url HTTP/1.1\\r\\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com` results in the server receiving an additional, attacker-controlled request:\n\n```http\nPOST /attacker-controlled-url HTTP/1.1\nHost: 727ymeu841qydmnwlol261ktkkqbe24qt.oastify.com\nContent-Length: 4\nContent-Type: application/x-www-form-urlencoded\n\nbody\n```\n\n### Impact\nApplications using the Tornado library to send HTTP requests with untrusted header data are affected. This issue may facilitate the exploitation of server-side request forgery (SSRF) vulnerabilities.",
      "cve": "GHSA-w235-7p84-xx57",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.4.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "GHSA-w235-7p84-xx57",
          "value": "GHSA-w235-7p84-xx57",
          "url": "https://scout.docker.com/v/GHSA-w235-7p84-xx57?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/GHSA-w235-7p84-xx57?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.0"
        }
      ]
    },
    {
      "id": "f81e55800d963d914802f0dde690bb5a1830e62971e798603b8bcba73187ce58",
      "category": "container_scanning",
      "message": "CVE-2023-34049 on salt@2019.2.3",
      "description": "The Salt-SSH pre-flight option copies the script to the target at a predictable path, which allows an attacker to force Salt-SSH to run their script. If an attacker has access to the target VM and knows the path to the pre-flight script before it runs they can ensure Salt-SSH runs their script with the privileges of the user running Salt-SSH. Do not make the copy path on the target predictable and ensure we check return codes of the scp command if the copy fails.",
      "cve": "CVE-2023-34049",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3005.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-34049",
          "value": "CVE-2023-34049",
          "url": "https://scout.docker.com/v/CVE-2023-34049?s=github&n=salt&t=pypi&vr=%3C3005.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-34049?s=github&n=salt&t=pypi&vr=%3C3005.4"
        }
      ]
    },
    {
      "id": "508db234804f804fe2962aa88229d09fb1692a880afd23cfabac4db1a6a32a1e",
      "category": "container_scanning",
      "message": "CVE-2023-5752 on pip@9.0.1",
      "description": "When installing a package from a Mercurial VCS URL, e.g. `pip install hg+...`, with pip prior to v23.3, the specified Mercurial revision could be used to inject arbitrary configuration options to the `hg clone` call (e.g. `--config`). Controlling the Mercurial configuration can modify how and which repository is installed. This vulnerability does not affect users who aren't installing from Mercurial.",
      "cve": "CVE-2023-5752",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade pip@9.0.1 to 23.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@9.0.1"
          },
          "version": "9.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-5752",
          "value": "CVE-2023-5752",
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ]
    },
    {
      "id": "d6bc551abf9d2408e2aaa2a59fb48d0e58a976688fc34834dcb56b2c1b7f0931",
      "category": "container_scanning",
      "message": "CVE-2023-23931 on cryptography@2.1.4",
      "description": "Previously, `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers:\n\n```pycon\n>>> outbuf = b\"\\x00\" * 32\n>>> c = ciphers.Cipher(AES(b\"\\x00\" * 32), modes.ECB()).encryptor()\n>>> c.update_into(b\"\\x00\" * 16, outbuf)\n16\n>>> outbuf\nb'\\xdc\\x95\\xc0x\\xa2@\\x89\\x89\\xadH\\xa2\\x14\\x92\\x84 \\x87\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'\n```\n\nThis would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python. This is a soundness bug -- it allows programmers to misuse an API, it cannot be exploited by attacker controlled data alone.\n\nThis now correctly raises an exception.\n\nThis issue has been present since `update_into` was originally introduced in cryptography 1.8.",
      "cve": "CVE-2023-23931",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 39.0.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-23931",
          "value": "CVE-2023-23931",
          "url": "https://scout.docker.com/v/CVE-2023-23931?s=github&n=cryptography&t=pypi&vr=%3E%3D1.8%2C%3C39.0.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-23931?s=github&n=cryptography&t=pypi&vr=%3E%3D1.8%2C%3C39.0.1"
        }
      ]
    },
    {
      "id": "ee4023822704fafc2fa0196c644bd147d966191a6e85876e00a1e26e6c3a62bb",
      "category": "container_scanning",
      "message": "CVE-2024-3651 on idna@2.6",
      "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
      "cve": "CVE-2024-3651",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade idna@2.6 to 3.7",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/idna@2.6"
          },
          "version": "2.6"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-3651",
          "value": "CVE-2024-3651",
          "url": "https://scout.docker.com/v/CVE-2024-3651?s=github&n=idna&t=pypi&vr=%3C3.7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-3651?s=github&n=idna&t=pypi&vr=%3C3.7"
        }
      ]
    },
    {
      "id": "9ad4fa9eb7c2f50077c52ba2e62fd62dea20cbc8e6a86ca3d527178a7e4a6e71",
      "category": "container_scanning",
      "message": "CVE-2023-24329 on ubuntu/python2.7@2.7.17-1~18.04ubuntu1.11",
      "description": "An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.",
      "cve": "CVE-2023-24329",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade ubuntu/python2.7@2.7.17-1~18.04ubuntu1.11 to 2.7.17-1~18.04ubuntu1.13",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/ubuntu/python2.7@2.7.17-1~18.04ubuntu1.11?os_distro=bionic&os_name=ubuntu&os_version=18.04"
          },
          "version": "2.7.17-1~18.04ubuntu1.11"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-24329",
          "value": "CVE-2023-24329",
          "url": "https://scout.docker.com/v/CVE-2023-24329?s=ubuntu&n=python2.7&ns=ubuntu&t=deb&osn=ubuntu&osv=18.04&vr=%3C2.7.17-1%7E18.04ubuntu1.13"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-24329?s=ubuntu&n=python2.7&ns=ubuntu&t=deb&osn=ubuntu&osv=18.04&vr=%3C2.7.17-1%7E18.04ubuntu1.13"
        }
      ]
    },
    {
      "id": "8ab896111aceb2a1cbe1bde61bd2401c8872fae9e131bd79f1111a7921aa6fd8",
      "category": "container_scanning",
      "message": "CVE-2020-11652 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 2019.2.4 and 3000 before 3000.2. The salt-master process ClearFuncs class allows access to some methods that improperly sanitize paths. These methods allow arbitrary directory access to authenticated users.",
      "cve": "CVE-2020-11652",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11652",
          "value": "CVE-2020-11652",
          "url": "https://scout.docker.com/v/CVE-2020-11652?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11652?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ]
    },
    {
      "id": "5862e1c773d48a9da1da21db5b5261e5f694fe7fe7ebc07d93df2dc6309ba7fc",
      "category": "container_scanning",
      "message": "CVE-2021-3572 on pip@9.0.1",
      "description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
      "cve": "CVE-2021-3572",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pip@9.0.1 to 21.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@9.0.1"
          },
          "version": "9.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3572",
          "value": "CVE-2021-3572",
          "url": "https://scout.docker.com/v/CVE-2021-3572?s=github&n=pip&t=pypi&vr=%3C21.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3572?s=github&n=pip&t=pypi&vr=%3C21.1"
        }
      ]
    },
    {
      "id": "37cac61b67756bd62c17703636121dca6d0afa703dc6212c255c759fd64c21ae",
      "category": "container_scanning",
      "message": "CVE-2020-35662 on salt@2019.2.3",
      "description": "In SaltStack Salt before 3002.5, when authenticating to services using certain modules, the SSL certificate is not always validated.",
      "cve": "CVE-2020-35662",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-35662",
          "value": "CVE-2020-35662",
          "url": "https://scout.docker.com/v/CVE-2020-35662?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-35662?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "dc8b64b7fda1e0be83aed04a6c542e8f08da25d9668b08768a4aa1a69f1ff0fc",
      "category": "container_scanning",
      "message": "CVE-2023-0286 on cryptography@2.1.4",
      "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8.1-39.0.0  are vulnerable to a security issue. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20221213.txt and https://www.openssl.org/news/secadv/20230207.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
      "cve": "CVE-2023-0286",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 39.0.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-0286",
          "value": "CVE-2023-0286",
          "url": "https://scout.docker.com/v/CVE-2023-0286?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8.1%2C%3C39.0.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-0286?s=github&n=cryptography&t=pypi&vr=%3E%3D0.8.1%2C%3C39.0.1"
        }
      ]
    },
    {
      "id": "89d9f357ce72991d12ce91b9ca5997c02dc9d0b411f997b47833a699a6be2d48",
      "category": "container_scanning",
      "message": "CVE-2019-12761 on pyxdg@0.25",
      "description": "A code injection issue was discovered in PyXDG before 0.26 via crafted Python code in a Category element of a Menu XML document in a .menu file. XDG_CONFIG_DIRS must be set up to trigger xdg.Menu.parse parsing within the directory containing this file. This is due to a lack of sanitization in xdg/Menu.py before an eval call.",
      "cve": "CVE-2019-12761",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pyxdg@0.25 to 0.26",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyxdg@0.25"
          },
          "version": "0.25"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-12761",
          "value": "CVE-2019-12761",
          "url": "https://scout.docker.com/v/CVE-2019-12761?s=github&n=pyxdg&t=pypi&vr=%3C0.26"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-12761?s=github&n=pyxdg&t=pypi&vr=%3C0.26"
        }
      ]
    },
    {
      "id": "f2bba63ad8950588c5db74f2073b1bca94bffbf215caf39b60cc80044395ff6d",
      "category": "container_scanning",
      "message": "CVE-2021-21996 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 3003.3. A user who has control of the source, and source_hash URLs can gain full file system access as root on a salt minion.",
      "cve": "CVE-2021-21996",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3003.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-21996",
          "value": "CVE-2021-21996",
          "url": "https://scout.docker.com/v/CVE-2021-21996?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-21996?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ]
    },
    {
      "id": "7f82ee0de29decc9a8aee49ea7817fbf239d20b85c7966fb006bbdbc6ac28ef9",
      "category": "container_scanning",
      "message": "CVE-2021-22004 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 3003.3. The salt minion installer will accept and use a minion config file at C:\\salt\\conf if that file is in place before the installer is run. This allows for a malicious actor to subvert the proper behaviour of the given minion software.",
      "cve": "CVE-2021-22004",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3003.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-22004",
          "value": "CVE-2021-22004",
          "url": "https://scout.docker.com/v/CVE-2021-22004?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-22004?s=github&n=salt&t=pypi&vr=%3C3003.3"
        }
      ]
    },
    {
      "id": "e9a69b35dfcaa42598d410df71f99bb932d7be2592c8c63ed7c65d36e242206b",
      "category": "container_scanning",
      "message": "CVE-2022-40898 on wheel@0.30.0",
      "description": "Python Packaging Authority (PyPA) Wheel is a reference implementation of the Python wheel packaging standard. Wheel 0.37.1 and earlier are vulnerable to a Regular Expression denial of service via attacker controlled input to the wheel cli. The vulnerable regex is used to verify the validity of Wheel file names. This has been patched in version 0.38.1.",
      "cve": "CVE-2022-40898",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade wheel@0.30.0 to 0.38.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/wheel@0.30.0"
          },
          "version": "0.30.0"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-40898",
          "value": "CVE-2022-40898",
          "url": "https://scout.docker.com/v/CVE-2022-40898?s=github&n=wheel&t=pypi&vr=%3C0.38.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-40898?s=github&n=wheel&t=pypi&vr=%3C0.38.1"
        }
      ]
    },
    {
      "id": "028cd7b2b12aa34fd6536a07d1fdb245beb7bb4e3ec9724698fba21969c50c89",
      "category": "container_scanning",
      "message": "CVE-2023-37920 on certifi@2021.10.8",
      "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
      "cve": "CVE-2023-37920",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade certifi@2021.10.8 to 2023.7.22",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/certifi@2021.10.8"
          },
          "version": "2021.10.8"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-37920",
          "value": "CVE-2023-37920",
          "url": "https://scout.docker.com/v/CVE-2023-37920?s=github&n=certifi&t=pypi&vr=%3E%3D2015.4.28%2C%3C2023.7.22"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-37920?s=github&n=certifi&t=pypi&vr=%3E%3D2015.4.28%2C%3C2023.7.22"
        }
      ]
    },
    {
      "id": "c061618a11d58e257f1c11150148d94e9c9458d8339f587075cbe5b6f91ce032",
      "category": "container_scanning",
      "message": "CVE-2024-52804 on tornado@5.1.1",
      "description": "The algorithm used for parsing HTTP cookies in Tornado versions prior to 6.4.2 sometimes has quadratic complexity, leading to excessive CPU consumption when parsing maliciously-crafted cookie headers. This parsing occurs in the event loop thread and may block the processing of other requests.\n\nSee also CVE-2024-7592 for a similar vulnerability in cpython.",
      "cve": "CVE-2024-52804",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.4.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-52804",
          "value": "CVE-2024-52804",
          "url": "https://scout.docker.com/v/CVE-2024-52804?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-52804?s=github&n=tornado&t=pypi&vr=%3C%3D6.4.1"
        }
      ]
    },
    {
      "id": "053cca2e20f9d70d83eb22a44b285e30784f1d4ccfc608b7791ab769eaddc40d",
      "category": "container_scanning",
      "message": "CVE-2024-6345 on setuptools@39.0.1",
      "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
      "cve": "CVE-2024-6345",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@39.0.1 to 70.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@39.0.1"
          },
          "version": "39.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-6345",
          "value": "CVE-2024-6345",
          "url": "https://scout.docker.com/v/CVE-2024-6345?s=github&n=setuptools&t=pypi&vr=%3C70.0.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-6345?s=github&n=setuptools&t=pypi&vr=%3C70.0.0"
        }
      ]
    },
    {
      "id": "ba61e92f915f1805c10c92a38a76c4fc4b51e948a2278c9b9a36a905ac4e2865",
      "category": "container_scanning",
      "message": "CVE-2025-47287 on tornado@5.1.1",
      "description": "### Summary\n\nWhen Tornado's ``multipart/form-data`` parser encounters certain errors, it logs a warning but continues trying to parse the remainder of the data. This allows remote attackers to generate an extremely high volume of logs, constituting a DoS attack. This DoS is compounded by the fact that the logging subsystem is synchronous.\n\n### Affected versions\n\nAll versions of Tornado prior to 6.5 are affected. The vulnerable parser is enabled by default.\n\n### Solution\n\nUpgrade to Tornado version 6.5. In the meantime, risk can be mitigated by blocking `Content-Type: multipart/form-data` in a proxy.",
      "cve": "CVE-2025-47287",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade tornado@5.1.1 to 6.5.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/tornado@5.1.1"
          },
          "version": "5.1.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-47287",
          "value": "CVE-2025-47287",
          "url": "https://scout.docker.com/v/CVE-2025-47287?s=github&n=tornado&t=pypi&vr=%3C6.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-47287?s=github&n=tornado&t=pypi&vr=%3C6.5"
        }
      ]
    },
    {
      "id": "5764aae90af401379b0584099f0360d8e33ddf59dea7a95d18c4c9e3788e6fc7",
      "category": "container_scanning",
      "message": "CVE-2022-22967 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.9, 3003.5, 3004.2. PAM auth fails to reject locked accounts, which allows a previously authorized user whose account is locked still run Salt commands when their account is locked. This affects both local shell accounts with an active session and salt-api users that authenticate via PAM eauth.",
      "cve": "CVE-2022-22967",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.9",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22967",
          "value": "CVE-2022-22967",
          "url": "https://scout.docker.com/v/CVE-2022-22967?s=github&n=salt&t=pypi&vr=%3C3002.9"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22967?s=github&n=salt&t=pypi&vr=%3C3002.9"
        }
      ]
    },
    {
      "id": "162c6767d6d5156a36b3b66c4889fde2f5eba34d4609f2c7e8da8b0bcff72730",
      "category": "container_scanning",
      "message": "CVE-2024-22232 on salt@2019.2.3",
      "description": "A specially crafted url can be created which leads to a directory traversal in the salt file server.\nA malicious user can read an arbitrary file from a Salt master’s filesystem.",
      "cve": "CVE-2024-22232",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3005.5",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-22232",
          "value": "CVE-2024-22232",
          "url": "https://scout.docker.com/v/CVE-2024-22232?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-22232?s=github&n=salt&t=pypi&vr=%3C3005.5"
        }
      ]
    },
    {
      "id": "a42faa6b99d7d946773b730db37df0320b07d04c1fa42394b31e7a92e9523a99",
      "category": "container_scanning",
      "message": "CVE-2025-47273 on setuptools@39.0.1",
      "description": "### Summary \nA path traversal vulnerability in `PackageIndex` was fixed in setuptools version 78.1.1\n\n### Details\n```\n    def _download_url(self, url, tmpdir):\n        # Determine download filename\n        #\n        name, _fragment = egg_info_for_url(url)\n        if name:\n            while '..' in name:\n                name = name.replace('..', '.').replace('\\\\', '_')\n        else:\n            name = \"__downloaded__\"  # default if URL has no path contents\n\n        if name.endswith('.[egg.zip](http://egg.zip/)'):\n            name = name[:-4]  # strip the extra .zip before download\n\n -->       filename = os.path.join(tmpdir, name)\n```\n\nHere: https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88\n\n`os.path.join()` discards the first argument `tmpdir` if the second begins with a slash or drive letter.\n`name` is derived from a URL without sufficient sanitization. While there is some attempt to sanitize by replacing instances of '..' with '.', it is insufficient.\n\n### Risk Assessment\nAs easy_install and package_index are deprecated, the exploitation surface is reduced.\nHowever, it seems this could be exploited in a similar fashion like https://github.com/advisories/GHSA-r9hx-vwmv-q579, and as described by POC 4 in https://github.com/advisories/GHSA-cx63-2mw6-8hw5 report: via malicious URLs present on the pages of a package index.\n\n### Impact\nAn attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to RCE depending on the context.\n\n### References\nhttps://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5\nhttps://github.com/pypa/setuptools/issues/4946",
      "cve": "CVE-2025-47273",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@39.0.1 to 78.1.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@39.0.1"
          },
          "version": "39.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-47273",
          "value": "CVE-2025-47273",
          "url": "https://scout.docker.com/v/CVE-2025-47273?s=github&n=setuptools&t=pypi&vr=%3C78.1.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-47273?s=github&n=setuptools&t=pypi&vr=%3C78.1.1"
        }
      ]
    },
    {
      "id": "33a909b936328780993c5d2d539650c0389f94aab120b2005179e3c85720f141",
      "category": "container_scanning",
      "message": "CVE-2020-28243 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. The minion's `restartcheck` is vulnerable to command injection via a crafted process name. This allows for a local privilege escalation by any user able to create a files on the minion in a non-blacklisted directory.",
      "cve": "CVE-2020-28243",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28243",
          "value": "CVE-2020-28243",
          "url": "https://scout.docker.com/v/CVE-2020-28243?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28243?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "1479afc69a7148b3aab36a7cf96721a0b15b66c1038b843a5eeece1c24b86a45",
      "category": "container_scanning",
      "message": "CVE-2021-25315 on salt@2019.2.3",
      "description": "A Incorrect Implementation of Authentication Algorithm vulnerability in of SUSE SUSE Linux Enterprise Server 15 SP 3; openSUSE Tumbleweed allows local attackers to execute arbitrary code via salt without the need to specify valid credentials. This issue affects: SUSE SUSE Linux Enterprise Server 15 SP 3 salt versions prior to 3002.2-3. openSUSE Tumbleweed salt version 3002.2-2.1 and prior versions.",
      "cve": "CVE-2021-25315",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25315",
          "value": "CVE-2021-25315",
          "url": "https://scout.docker.com/v/CVE-2021-25315?s=github&n=salt&t=pypi&vr=%3C3002.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25315?s=github&n=salt&t=pypi&vr=%3C3002.2"
        }
      ]
    },
    {
      "id": "ae310ebba6abb63976179016a5e9bd2135212b3b7d62e55bda609b191d555d92",
      "category": "container_scanning",
      "message": "CVE-2021-31607 on salt@2019.2.3",
      "description": "In SaltStack Salt 2016.9 through 3002.6, a command injection vulnerability exists in the snapper module that allows for local privilege escalation on a minion. The attack requires that a file is created with a pathname that is backed up by snapper, and that the master calls the snapper.diff function (which executes popen unsafely).",
      "cve": "CVE-2021-31607",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3003rc1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-31607",
          "value": "CVE-2021-31607",
          "url": "https://scout.docker.com/v/CVE-2021-31607?s=github&n=salt&t=pypi&vr=%3E%3D2016.11.0%2C%3C%3D3002.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-31607?s=github&n=salt&t=pypi&vr=%3E%3D2016.11.0%2C%3C%3D3002.6"
        }
      ]
    },
    {
      "id": "d4f04f963cb22faf03926b2ead785b6d5cc532cbc3c340ae47474ad360f7e737",
      "category": "container_scanning",
      "message": "CVE-2020-25659 on cryptography@2.1.4",
      "description": "RSA decryption was vulnerable to Bleichenbacher timing vulnerabilities, which would impact people using RSA decryption in online scenarios. This is fixed in cryptography 3.2. ",
      "cve": "CVE-2020-25659",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 3.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-25659",
          "value": "CVE-2020-25659",
          "url": "https://scout.docker.com/v/CVE-2020-25659?s=github&n=cryptography&t=pypi&vr=%3C3.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-25659?s=github&n=cryptography&t=pypi&vr=%3C3.2"
        }
      ]
    },
    {
      "id": "07e10e4e72a2670efd722ebfbc62ef97d96dedaf103af9168cf6f93e3fcb900b",
      "category": "container_scanning",
      "message": "CVE-2020-28972 on salt@2019.2.3",
      "description": "In SaltStack Salt before 3002.5, authentication to VMware vcenter, vsphere, and esxi servers (in the `vmware.py` files) does not always validate the SSL/TLS certificate.",
      "cve": "CVE-2020-28972",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-28972",
          "value": "CVE-2020-28972",
          "url": "https://scout.docker.com/v/CVE-2020-28972?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-28972?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "46aad2399bfdec80e8235446677a6804d47a3cb7221225df01660fb744bfc0f2",
      "category": "container_scanning",
      "message": "CVE-2018-10903 on cryptography@2.1.4",
      "description": "A flaw was found in python-cryptography versions between >=1.9.0 and <2.3. The finalize_with_tag API did not enforce a minimum tag length. If a user did not validate the input length prior to passing it to finalize_with_tag an attacker could craft an invalid payload with a shortened tag (e.g. 1 byte) such that they would have a 1 in 256 chance of passing the MAC check. GCM tag forgeries can cause key leakage.",
      "cve": "CVE-2018-10903",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 2.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2018-10903",
          "value": "CVE-2018-10903",
          "url": "https://scout.docker.com/v/CVE-2018-10903?s=github&n=cryptography&t=pypi&vr=%3E%3D1.9.0%2C%3C2.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2018-10903?s=github&n=cryptography&t=pypi&vr=%3E%3D1.9.0%2C%3C2.3"
        }
      ]
    },
    {
      "id": "8e144da9a112a3da7ab6da934024076fd7d3f637113e464b0179999d851cc84c",
      "category": "container_scanning",
      "message": "CVE-2018-6594 on pycrypto@2.6.1",
      "description": "lib/Crypto/PublicKey/ElGamal.py in PyCrypto through 2.6.1 generates weak ElGamal key parameters, which allows attackers to obtain sensitive information by reading ciphertext data (i.e., it does not have semantic security in face of a ciphertext-only attack). The Decisional Diffie-Hellman (DDH) assumption does not hold for PyCrypto's ElGamal implementation.",
      "cve": "CVE-2018-6594",
      "severity": "High",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pycrypto@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2018-6594",
          "value": "CVE-2018-6594",
          "url": "https://scout.docker.com/v/CVE-2018-6594?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2018-6594?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ]
    },
    {
      "id": "45ea502ae01b2bc23b351b28990e159bfa0d3ae2eb39ed449ff559c6007aa611",
      "category": "container_scanning",
      "message": "CVE-2019-20916 on pip@9.0.1",
      "description": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py. A fix was committed 6704f2ace.",
      "cve": "CVE-2019-20916",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade pip@9.0.1 to 19.2",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@9.0.1"
          },
          "version": "9.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-20916",
          "value": "CVE-2019-20916",
          "url": "https://scout.docker.com/v/CVE-2019-20916?s=github&n=pip&t=pypi&vr=%3C19.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-20916?s=github&n=pip&t=pypi&vr=%3C19.2"
        }
      ]
    },
    {
      "id": "4c2b5da6446c3ef930f3b49c652f44de9c7a91f553694c84bb387dcc243d6fe5",
      "category": "container_scanning",
      "message": "CVE-2022-22934 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. Salt Masters do not sign pillar data with the minion’s public key, which can result in attackers substituting arbitrary pillar data.",
      "cve": "CVE-2022-22934",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22934",
          "value": "CVE-2022-22934",
          "url": "https://scout.docker.com/v/CVE-2022-22934?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22934?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "0f04a61469d8c667921c098394dba1984e6ddcf4e6c3cadd9a77f85aab52622c",
      "category": "container_scanning",
      "message": "CVE-2022-40897 on setuptools@39.0.1",
      "description": "Python Packaging Authority (PyPA)'s setuptools is a library designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a vulnerable Regular Expression in `package_index`. This has been patched in version 65.5.1.",
      "cve": "CVE-2022-40897",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade setuptools@39.0.1 to 65.5.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/setuptools@39.0.1"
          },
          "version": "39.0.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-40897",
          "value": "CVE-2022-40897",
          "url": "https://scout.docker.com/v/CVE-2022-40897?s=github&n=setuptools&t=pypi&vr=%3C65.5.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-40897?s=github&n=setuptools&t=pypi&vr=%3C65.5.1"
        }
      ]
    },
    {
      "id": "a97a0ac3bb3489c419a2cae2950989dd904b075fcd28c8863cc9ffc10b192709",
      "category": "container_scanning",
      "message": "CVE-2023-50782 on cryptography@2.1.4",
      "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
      "cve": "CVE-2023-50782",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade cryptography@2.1.4 to 42.0.0",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/cryptography@2.1.4"
          },
          "version": "2.1.4"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-50782",
          "value": "CVE-2023-50782",
          "url": "https://scout.docker.com/v/CVE-2023-50782?s=github&n=cryptography&t=pypi&vr=%3C42.0.0"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-50782?s=github&n=cryptography&t=pypi&vr=%3C42.0.0"
        }
      ]
    },
    {
      "id": "7d37eabfd7fbd4a41d8e75d3534ab45f39a02c6cec6045429d73ecad1ba300f0",
      "category": "container_scanning",
      "message": "CVE-2021-25282 on salt@2019.2.3",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. The `salt.wheel.pillar_roots.write` method is vulnerable to directory traversal.",
      "cve": "CVE-2021-25282",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25282",
          "value": "CVE-2021-25282",
          "url": "https://scout.docker.com/v/CVE-2021-25282?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25282?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "4ff280b6325b32721dc9704eaf3240ccb4027cc9c1da5df8a1b8911257022906",
      "category": "container_scanning",
      "message": "CVE-2022-22936 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. Job publishes and file server replies are susceptible to replay attacks, which can result in an attacker replaying job publishes causing minions to run old jobs. File server replies can also be re-played. A sufficient craft attacker could gain root access on minion under certain scenarios.",
      "cve": "CVE-2022-22936",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22936",
          "value": "CVE-2022-22936",
          "url": "https://scout.docker.com/v/CVE-2022-22936?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22936?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "b9ac66afa80e5b8f1bdf7f79cab295a66402aedb601488e331888e39e191f844",
      "category": "container_scanning",
      "message": "CVE-2022-22941 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt in versions before 3002.8, 3003.4, 3004.1. When configured as a Master-of-Masters, with a publisher_acl, if a user configured in the publisher_acl targets any minion connected to the Syndic, the Salt Master incorrectly interpreted no valid targets as valid, allowing configured users to target any of the minions connected to the syndic with their configured commands. This requires a syndic master combined with publisher_acl configured on the Master-of-Masters, allowing users specified in the publisher_acl to bypass permissions, publishing authorized commands to any configured minion.",
      "cve": "CVE-2022-22941",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3002.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-22941",
          "value": "CVE-2022-22941",
          "url": "https://scout.docker.com/v/CVE-2022-22941?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-22941?s=github&n=salt&t=pypi&vr=%3C3002.8"
        }
      ]
    },
    {
      "id": "b5bdf457d2594efc1939780571356f7a9d088d58a1e5aa236c4f58745fc58ea3",
      "category": "container_scanning",
      "message": "CVE-2021-3144 on salt@2019.2.3",
      "description": "In SaltStack Salt before 3002.5, eauth tokens can be used once after expiration. (They might be used to run command against the salt master or minions.)",
      "cve": "CVE-2021-3144",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3144",
          "value": "CVE-2021-3144",
          "url": "https://scout.docker.com/v/CVE-2021-3144?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3144?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "86481e8080bcaa918d23e55c729380385d78d259b75d47c165de72c7713abf0c",
      "category": "container_scanning",
      "message": "CVE-2013-7459 on pycrypto@2.6.1",
      "description": "Heap-based buffer overflow in the ALGnew function in block_templace.c in Python Cryptography Toolkit (aka pycrypto) allows remote attackers to execute arbitrary code as demonstrated by a crafted iv parameter to cryptmsg.py.",
      "cve": "CVE-2013-7459",
      "severity": "Critical",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pycrypto@2.6.1"
          },
          "version": "2.6.1"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2013-7459",
          "value": "CVE-2013-7459",
          "url": "https://scout.docker.com/v/CVE-2013-7459?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2013-7459?s=github&n=pycrypto&t=pypi&vr=%3C%3D2.6.1"
        }
      ]
    },
    {
      "id": "4cb5db20fc203f43aaeb705650c01e5d4ff0f375e7fe93647182d218a8a11b34",
      "category": "container_scanning",
      "message": "CVE-2020-11651 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 2019.2.4 and 3000 before 3000.2. The salt-master process ClearFuncs class does not properly validate method calls. This allows a remote user to access some methods without authentication. These methods can be used to retrieve user tokens from the salt master and/or run arbitrary commands on salt minions.",
      "cve": "CVE-2020-11651",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-11651",
          "value": "CVE-2020-11651",
          "url": "https://scout.docker.com/v/CVE-2020-11651?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-11651?s=github&n=salt&t=pypi&vr=%3C2019.2.4"
        }
      ]
    },
    {
      "id": "e0812b765e3c09cabea5704b3266da0109cd39e5e42012fae3227ee9147bfc40",
      "category": "container_scanning",
      "message": "CVE-2020-14343 on pyyaml@3.13",
      "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
      "cve": "CVE-2020-14343",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade pyyaml@3.13 to 5.4",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyyaml@3.13"
          },
          "version": "3.13"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-14343",
          "value": "CVE-2020-14343",
          "url": "https://scout.docker.com/v/CVE-2020-14343?s=github&n=pyyaml&t=pypi&vr=%3C5.4"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-14343?s=github&n=pyyaml&t=pypi&vr=%3C5.4"
        }
      ]
    },
    {
      "id": "5156018124811273cd7850daed0f710b96f3e68b5e90ab993643e4a6a800f3a6",
      "category": "container_scanning",
      "message": "CVE-2017-18342 on pyyaml@3.13",
      "description": "In PyYAML before 4.1, the `yaml.load()` API could execute arbitrary code. In other words, `yaml.safe_load` is not used.",
      "cve": "CVE-2017-18342",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade pyyaml@3.13 to 4.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pyyaml@3.13"
          },
          "version": "3.13"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2017-18342",
          "value": "CVE-2017-18342",
          "url": "https://scout.docker.com/v/CVE-2017-18342?s=github&n=pyyaml&t=pypi&vr=%3C4.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2017-18342?s=github&n=pyyaml&t=pypi&vr=%3C4.1"
        }
      ]
    },
    {
      "id": "6f85646335031a9f8cc650a88766695fa7e99e2f716459f57b4a295af144b6c2",
      "category": "container_scanning",
      "message": "CVE-2020-16846 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt through 3002. Sending crafted web requests to the Salt API, with the SSH client enabled, can result in shell injection.",
      "cve": "CVE-2020-16846",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.6",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-16846",
          "value": "CVE-2020-16846",
          "url": "https://scout.docker.com/v/CVE-2020-16846?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-16846?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.6"
        }
      ]
    },
    {
      "id": "40d5cbb416bdbe8e788dc82a80dfff64c8981fd4bf1b1c6e0a455e79be43919e",
      "category": "container_scanning",
      "message": "CVE-2020-25592 on salt@2019.2.3",
      "description": "In SaltStack the salt-netapi improperly validates eauth credentials and tokens. A user can bypass authentication and invoke Salt SSH.",
      "cve": "CVE-2020-25592",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.7",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2020-25592",
          "value": "CVE-2020-25592",
          "url": "https://scout.docker.com/v/CVE-2020-25592?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2020-25592?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.7"
        }
      ]
    },
    {
      "id": "2e4a4ef824ecaf53005f88f14168d7a33751df8ade007b3b0ed1f37d317884ec",
      "category": "container_scanning",
      "message": "CVE-2021-25281 on salt@2019.2.3",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. salt-api does not honor eauth credentials for the wheel_async client. Thus, an attacker can remotely run any wheel modules on the master.",
      "cve": "CVE-2021-25281",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25281",
          "value": "CVE-2021-25281",
          "url": "https://scout.docker.com/v/CVE-2021-25281?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25281?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "dd5140f725f092db6f5aad65578c56ee530263a381b7a31b901972f17d7f99cd",
      "category": "container_scanning",
      "message": "CVE-2021-25283 on salt@2019.2.3",
      "description": "An issue was discovered in through SaltStack Salt before 3002.5. The jinja renderer does not protect against server side template injection attacks.",
      "cve": "CVE-2021-25283",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-25283",
          "value": "CVE-2021-25283",
          "url": "https://scout.docker.com/v/CVE-2021-25283?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-25283?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "23cef529e2083e0799fac58c77232cd81354e1213cd60971670bb20d7d94486d",
      "category": "container_scanning",
      "message": "CVE-2021-3148 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. Sending crafted web requests to the Salt API can result in `salt.utils.thin.gen_thin()` command injection because of different handling of single versus double quotes. This is related to `salt/utils/thin.py`.",
      "cve": "CVE-2021-3148",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3148",
          "value": "CVE-2021-3148",
          "url": "https://scout.docker.com/v/CVE-2021-3148?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3148?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "6a403fb054d0889b67e0052a79b1ceb1576d7fb7243a846b0c8a20fb64661bd1",
      "category": "container_scanning",
      "message": "CVE-2021-3197 on salt@2019.2.3",
      "description": "An issue was discovered in SaltStack Salt before 3002.5. The salt-api's ssh client is vulnerable to a shell injection by including ProxyCommand in an argument, or via ssh_options provided in an API request.",
      "cve": "CVE-2021-3197",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 2019.2.8",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-3197",
          "value": "CVE-2021-3197",
          "url": "https://scout.docker.com/v/CVE-2021-3197?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-3197?s=github&n=salt&t=pypi&vr=%3E%3D2019.2.0%2C%3C2019.2.8"
        }
      ]
    },
    {
      "id": "3d11e5c7b759aa458586f0c4100c5ccb8628963f509e37062627d23868144b4c",
      "category": "container_scanning",
      "message": "CVE-2021-33226 on salt@2019.2.3",
      "description": "Buffer Overflow vulnerability in Saltstack v.3003 and before allows attacker to execute arbitrary code via the func variable in salt/salt/modules/status.py file.",
      "cve": "CVE-2021-33226",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade salt@2019.2.3 to 3003.1",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/salt@2019.2.3"
          },
          "version": "2019.2.3"
        },
        "operating_system": "ubuntu 18.04",
        "image": "custom_no_tool-salt-master:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-33226",
          "value": "CVE-2021-33226",
          "url": "https://scout.docker.com/v/CVE-2021-33226?s=pypa&n=salt&t=pypi&vr=%3C3003.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-33226?s=pypa&n=salt&t=pypi&vr=%3C3003.1"
        }
      ]
    }
  ],
  "remediations": [],
  "scan": {
    "start_time": "2025-09-17T22:25:34",
    "end_time": "2025-09-17T22:25:34",
    "status": "success",
    "type": "container_scanning",
    "scanner": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    },
    "analyzer": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    }
  }
}
