time="2025-10-31T22:29:51+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-20933/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 703B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 181B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 DONE 1.1s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 805B done
#5 DONE 0.0s

#6 [1/5] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#6 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#6 DONE 0.0s

#7 [2/5] WORKDIR /app
#7 CACHED

#8 [3/5] COPY requirements.txt .
#8 DONE 0.0s

#9 [4/5] RUN pip install --no-cache-dir -r requirements.txt
#9 1.966 Collecting Flask==2.0.1
#9 2.167   Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
#9 2.192      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 4.2 MB/s eta 0:00:00
#9 2.339 Collecting PyYAML==3.12
#9 2.361   Downloading PyYAML-3.12.zip (375 kB)
#9 2.411      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.8/375.8 kB 7.7 MB/s eta 0:00:00
#9 2.508   Preparing metadata (setup.py): started
#9 2.962   Preparing metadata (setup.py): finished with status 'done'
#9 3.016 Collecting Jinja2>=3.0
#9 3.036   Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
#9 3.048      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 17.2 MB/s eta 0:00:00
#9 3.116 Collecting Werkzeug>=2.0
#9 3.135   Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
#9 3.168      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 7.5 MB/s eta 0:00:00
#9 3.211 Collecting itsdangerous>=2.0
#9 3.230   Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 3.283 Collecting click>=7.1.2
#9 3.302   Downloading click-8.1.8-py3-none-any.whl (98 kB)
#9 3.314      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 9.6 MB/s eta 0:00:00
#9 3.478 Collecting MarkupSafe>=2.0
#9 3.497   Downloading markupsafe-3.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (20 kB)
#9 3.508 Building wheels for collected packages: PyYAML
#9 3.510   Building wheel for PyYAML (setup.py): started
#9 3.738   Building wheel for PyYAML (setup.py): finished with status 'done'
#9 3.739   Created wheel for PyYAML: filename=pyyaml-3.12-cp39-cp39-linux_x86_64.whl size=43156 sha256=d34ed4f8bccdd575127cc68444e0479dac50d9afafc326c2f9831b5bfad19c1b
#9 3.739   Stored in directory: /tmp/pip-ephem-wheel-cache-ivijuyto/wheels/d2/35/d6/9853325318cff4c6fee7514905a5931993a2230e2b746fc978
#9 3.742 Successfully built PyYAML
#9 3.802 Installing collected packages: PyYAML, MarkupSafe, itsdangerous, click, Werkzeug, Jinja2, Flask
#9 4.166 Successfully installed Flask-2.0.1 Jinja2-3.1.6 MarkupSafe-3.0.3 PyYAML-3.12 Werkzeug-3.1.3 click-8.1.8 itsdangerous-2.2.0
#9 4.166 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 4.315 
#9 4.315 [notice] A new release of pip is available: 23.0.1 -> 25.3
#9 4.315 [notice] To update, run: pip install --upgrade pip
#9 DONE 4.5s

#10 [5/5] COPY . .
#10 DONE 0.0s

#11 exporting to image
#11 exporting layers
#11 exporting layers 0.6s done
#11 exporting manifest sha256:478afda3a8ee282098bfc66521ffd820959d0e4bd9dd4d1d5e994b92b2126759 0.0s done
#11 exporting config sha256:574d2c9c960defbf37bc28017ec6591b77225951e383a755fd6c94ec6091e0cd 0.0s done
#11 exporting attestation manifest sha256:eb554d84ed88230f30882f203c818ed9dac7b3433003225d3b73a54daa7b15a1 0.0s done
#11 exporting manifest list sha256:239b0082c54c7b26d0c44944170bc5f9883bcf8cec78388bd799c1fb3f836a94 0.0s done
#11 naming to docker.io/library/custom_no_tool-web:latest done
#11 unpacking to docker.io/library/custom_no_tool-web:latest
#11 unpacking to docker.io/library/custom_no_tool-web:latest 0.3s done
#11 DONE 1.0s

#12 resolving provenance for metadata file
#12 DONE 0.0s
 custom_no_tool-web  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container custom_no_tool-web-1  Creating
 Container custom_no_tool-web-1  Created
 Container custom_no_tool-web-1  Starting
 Container custom_no_tool-web-1  Started


sudo docker logs ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)
 Traceback (most recent call last):
   File "/app/app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
     from .app import Flask as Flask
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
     from . import cli
   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
     from .helpers import get_debug_flag
   File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 16, in <module>
     from werkzeug.urls import url_quote
 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/site-packages/werkzeug/urls.py)




sudo docker inspect ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2[
    {
        "Id": "ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2",
        "Created": "2025-10-31T21:29:58.358344559Z",
        "Path": "python",
        "Args": [
            "app.py"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-31T21:30:27.021928256Z",
            "FinishedAt": "2025-10-31T21:30:27.553571276Z"
        },
        "Image": "sha256:239b0082c54c7b26d0c44944170bc5f9883bcf8cec78388bd799c1fb3f836a94",
        "ResolvConfPath": "/var/lib/docker/containers/ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2/hostname",
        "HostsPath": "/var/lib/docker/containers/ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2/hosts",
        "LogPath": "/var/lib/docker/containers/ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2/ce42741d20143bc62ed5d86e218dcaee9210087c8447da8e23b0a0d9b17dcec2-json.log",
        "Name": "/custom_no_tool-web-1",
        "RestartCount": 9,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "5000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "ce42741d2014",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "FLASK_APP=app.py",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.24",
                "PYTHON_SHA256=668391afabd5083faafa4543753d190f82f33ce6ba22d6e9ac728b43644b278a"
            ],
            "Cmd": [
                "python",
                "app.py"
            ],
            "Image": "custom_no_tool-web",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "86487189e08cc17a49315eb108cbb775eb83a8faa1fd28a2b413ef0ad71cfc46",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:239b0082c54c7b26d0c44944170bc5f9883bcf8cec78388bd799c1fb3f836a94",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-20933/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-20933/custom_no_tool",
                "com.docker.compose.service": "web",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-web-1",
                        "web"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "537efb972003b75d25d4c797a8c4db8d803cf589ed86d0c42aca0507b41eafb6",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-web-1",
                        "web",
                        "ce42741d2014"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:478afda3a8ee282098bfc66521ffd820959d0e4bd9dd4d1d5e994b92b2126759",
            "size": 1810,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]