 exploit_runner Pulling 
 exploit_runner Error failed to resolve reference "docker.io/library/docker:18.06.1-cli": docker.io/library/docker:18.06.1-cli: not found
Error response from daemon: failed to resolve reference "docker.io/library/docker:18.06.1-cli": docker.io/library/docker:18.06.1-cli: not found
