time="2025-10-23T17:03:29+02:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-11651/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 723B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 153B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.8
#3 DONE 0.0s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/4] FROM docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c
#5 resolve docker.io/library/python:3.8@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c 0.0s done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 446B done
#6 DONE 0.0s

#7 [2/4] WORKDIR /scripts
#7 CACHED

#8 [3/4] COPY exploit.py /scripts/
#8 DONE 0.0s

#9 [4/4] RUN pip install requests
#9 1.609 Collecting requests
#9 1.779   Downloading requests-2.32.4-py3-none-any.whl (64 kB)
#9 1.825      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 2.4 MB/s eta 0:00:00
#9 1.891 Collecting certifi>=2017.4.17
#9 1.914   Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
#9 1.954      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 4.1 MB/s eta 0:00:00
#9 1.992 Collecting idna<4,>=2.5
#9 2.015   Downloading idna-3.11-py3-none-any.whl (71 kB)
#9 2.040      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 2.7 MB/s eta 0:00:00
#9 2.114 Collecting urllib3<3,>=1.21.1
#9 2.137   Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
#9 2.150      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 11.4 MB/s eta 0:00:00
#9 2.374 Collecting charset_normalizer<4,>=2
#9 2.403   Downloading charset_normalizer-3.4.4-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (147 kB)
#9 2.431      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.6/147.6 kB 6.0 MB/s eta 0:00:00
#9 2.479 Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
#9 2.692 Successfully installed certifi-2025.10.5 charset_normalizer-3.4.4 idna-3.11 requests-2.32.4 urllib3-2.2.3
#9 2.692 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 2.846 
#9 2.846 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
#9 2.846 [notice] To update, run: pip install --upgrade pip
#9 DONE 2.9s

#10 exporting to image
#10 exporting layers
#10 exporting layers 0.5s done
#10 exporting manifest sha256:fb0cd242900d18562f392c103a143e37079c31e51e23dc8250ac6191be096d4a done
#10 exporting config sha256:f9d0154300353fe2230452af9df3204a5839dd925cb31cdc0dbbc76e199515a0 done
#10 exporting attestation manifest sha256:9cc07dfcbd5e477721d58ffb3e27ec69931decf674acf7387f5394d8ff542341 0.0s done
#10 exporting manifest list sha256:d7185c06b820815834c6036d423857ecbf53a0b8d22e02df3f2d2c3e431aad7b done
#10 naming to docker.io/library/custom_no_tool-python:latest done
#10 unpacking to docker.io/library/custom_no_tool-python:latest
#10 unpacking to docker.io/library/custom_no_tool-python:latest 0.2s done
#10 DONE 0.8s

#11 resolving provenance for metadata file
#11 DONE 0.0s
 custom_no_tool-python  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container salt-master  Creating
 Container salt-master  Created
 Container python  Creating
 Container salt-minion  Creating
 Container salt-minion  Created
 Container python  Created
 Container salt-master  Starting
 Container salt-master  Started
 Container python  Starting
 Container salt-minion  Starting
 Container salt-minion  Started
 Container python  Started


sudo docker logs 26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 199, in _new_conn
     sock = connection.create_connection(
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
     raise err
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
     sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
     response = self._make_request(
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 495, in _make_request
     conn.request(
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 441, in request
     self.endheaders()
   File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.8/http/client.py", line 951, in send
     self.connect()
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 279, in connect
     self.sock = self._new_conn()
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in _new_conn
     raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7461f1211fd0>: Failed to establish a new connection: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 519, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7461f1211fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "exploit.py", line 18, in <module>
     exploit_salt_master('localhost')
   File "exploit.py", line 14, in exploit_salt_master
     response = requests.post(url, json=data, headers=headers)
   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 115, in post
     return request("post", url, data=data, json=json, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 59, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7461f1211fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))




sudo docker inspect 26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0[
    {
        "Id": "26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0",
        "Created": "2025-10-23T15:03:33.820227357Z",
        "Path": "python",
        "Args": [
            "exploit.py"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-23T15:03:34.209903957Z",
            "FinishedAt": "2025-10-23T15:03:34.656285507Z"
        },
        "Image": "sha256:d7185c06b820815834c6036d423857ecbf53a0b8d22e02df3f2d2c3e431aad7b",
        "ResolvConfPath": "/var/lib/docker/containers/26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0/hostname",
        "HostsPath": "/var/lib/docker/containers/26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0/hosts",
        "LogPath": "/var/lib/docker/containers/26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0/26a714a8c8a1bd55c27207dbf5fd1ca6ed66d85cbf126c55c4daecce164707f0-json.log",
        "Name": "/python",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-11651/custom_no_tool/scripts:/scripts:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-11651/custom_no_tool/scripts",
                "Destination": "/scripts",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "26a714a8c8a1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.20"
            ],
            "Cmd": null,
            "Image": "custom_no_tool-python",
            "Volumes": null,
            "WorkingDir": "/scripts",
            "Entrypoint": [
                "python",
                "exploit.py"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "6a9be1c79fb28a80739953029a9d07baa609a8d1e68b4b7a9ccde1ee38ae3960",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "salt-master:service_started:false",
                "com.docker.compose.image": "sha256:d7185c06b820815834c6036d423857ecbf53a0b8d22e02df3f2d2c3e431aad7b",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-11651/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2020-11651/custom_no_tool",
                "com.docker.compose.service": "python",
                "com.docker.compose.version": "2.40.0",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "python",
                        "python"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "8258876874ee7b3f672c62a3f4fe057aabc70b244284a67853a5059b5706342b",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "python",
                        "26a714a8c8a1"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:fb0cd242900d18562f392c103a143e37079c31e51e23dc8250ac6191be096d4a",
            "size": 2202,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]