time="2025-10-29T15:53:23+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-45232/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 703B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 143B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 DONE 0.4s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/4] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#5 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 1.03kB done
#6 DONE 0.0s

#7 [2/4] WORKDIR /app
#7 CACHED

#8 [3/4] COPY . /app
#8 DONE 0.0s

#9 [4/4] RUN pip install -r requirements.txt
#9 1.639 Collecting Flask==2.0.3
#9 1.704   Downloading Flask-2.0.3-py3-none-any.whl (95 kB)
#9 1.728      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 4.2 MB/s eta 0:00:00
#9 1.797 Collecting docker==5.0.3
#9 1.813   Downloading docker-5.0.3-py2.py3-none-any.whl (146 kB)
#9 1.835      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.2/146.2 kB 7.8 MB/s eta 0:00:00
#9 1.909 Collecting Werkzeug==2.2.3
#9 1.926   Downloading Werkzeug-2.2.3-py3-none-any.whl (233 kB)
#9 1.955      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 8.8 MB/s eta 0:00:00
#9 2.015 Collecting click>=7.1.2
#9 2.030   Downloading click-8.1.8-py3-none-any.whl (98 kB)
#9 2.044      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 9.7 MB/s eta 0:00:00
#9 2.084 Collecting itsdangerous>=2.0
#9 2.101   Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 2.157 Collecting Jinja2>=3.0
#9 2.175   Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
#9 2.191      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 9.3 MB/s eta 0:00:00
#9 2.293 Collecting requests!=2.18.0,>=2.14.2
#9 2.309   Downloading requests-2.32.5-py3-none-any.whl (64 kB)
#9 2.322      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 7.2 MB/s eta 0:00:00
#9 2.381 Collecting websocket-client>=0.32.0
#9 2.395   Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
#9 2.406      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.6/82.6 kB 8.5 MB/s eta 0:00:00
#9 2.588 Collecting MarkupSafe>=2.1.1
#9 2.605   Downloading markupsafe-3.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (20 kB)
#9 2.675 Collecting idna<4,>=2.5
#9 2.690   Downloading idna-3.11-py3-none-any.whl (71 kB)
#9 2.705      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 11.4 MB/s eta 0:00:00
#9 2.799 Collecting urllib3<3,>=1.21.1
#9 2.813   Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
#9 2.828      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 10.2 MB/s eta 0:00:00
#9 3.092 Collecting charset_normalizer<4,>=2
#9 3.107   Downloading charset_normalizer-3.4.4-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (153 kB)
#9 3.127      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.0/154.0 kB 8.0 MB/s eta 0:00:00
#9 3.183 Collecting certifi>=2017.4.17
#9 3.213   Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
#9 3.248      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 4.7 MB/s eta 0:00:00
#9 3.373 Installing collected packages: websocket-client, urllib3, MarkupSafe, itsdangerous, idna, click, charset_normalizer, certifi, Werkzeug, requests, Jinja2, Flask, docker
#9 4.078 Successfully installed Flask-2.0.3 Jinja2-3.1.6 MarkupSafe-3.0.3 Werkzeug-2.2.3 certifi-2025.10.5 charset_normalizer-3.4.4 click-8.1.8 docker-5.0.3 idna-3.11 itsdangerous-2.2.0 requests-2.32.5 urllib3-2.5.0 websocket-client-1.9.0
#9 4.078 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 4.259 
#9 4.259 [notice] A new release of pip is available: 23.0.1 -> 25.3
#9 4.259 [notice] To update, run: pip install --upgrade pip
#9 DONE 4.4s

#10 exporting to image
#10 exporting layers
#10 exporting layers 0.8s done
#10 exporting manifest sha256:347fbf4c930e511cda2d1f91ae453e508db5f43f27550673fe94fcdd22c897e9 0.0s done
#10 exporting config sha256:7765d2d710a8bd165a03a766265f67fea7a8e5f9fa5037e60b5adf0e9c21e22d 0.0s done
#10 exporting attestation manifest sha256:0fcd3082c8d18eee1fb01ded0d5fc7c6b9468977cdbbeb25fc137613092abd19 0.0s done
#10 exporting manifest list sha256:a293164d4dbb941a5999d82a4489b51862c011a84bc92ff9f1ae94b01afc51b7 0.0s done
#10 naming to docker.io/library/custom_no_tool-app:latest done
#10 unpacking to docker.io/library/custom_no_tool-app:latest
#10 unpacking to docker.io/library/custom_no_tool-app:latest 0.4s done
#10 DONE 1.2s

#11 resolving provenance for metadata file
#11 DONE 0.0s
 custom_no_tool-app  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container custom_no_tool-dind-1  Creating
 Container custom_no_tool-dind-1  Created
 Container custom_no_tool-app-1  Creating
 Container custom_no_tool-app-1  Created
 Container custom_no_tool-dind-1  Starting
 Container custom_no_tool-dind-1  Started
 Container custom_no_tool-app-1  Starting
 Container custom_no_tool-app-1  Started


sudo docker logs 679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
     sock = connection.create_connection(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
     raise err
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
     sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
     response = self._make_request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 493, in _make_request
     conn.request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 494, in request
     self.endheaders()
   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
     self.connect()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 325, in connect
     self.sock = self._new_conn()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 213, in _new_conn
     raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7abec7c20160>: Failed to establish a new connection: [Errno 111] Connection refused
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 644, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='dind', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7abec7c20160>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
     return f(self, *args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 677, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='dind', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7abec7c20160>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/app/app.py", line 7, in <module>
     client = docker.DockerClient(base_url=os.getenv('DOCKER_HOST', 'tcp://dind:2375'))
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='dind', port=2375): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7abec7c20160>: Failed to establish a new connection: [Errno 111] Connection refused'))




sudo docker inspect 679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec[
    {
        "Id": "679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec",
        "Created": "2025-10-29T14:53:30.201317857Z",
        "Path": "python",
        "Args": [
            "app.py"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-29T14:53:30.55041888Z",
            "FinishedAt": "2025-10-29T14:53:31.269865435Z"
        },
        "Image": "sha256:a293164d4dbb941a5999d82a4489b51862c011a84bc92ff9f1ae94b01afc51b7",
        "ResolvConfPath": "/var/lib/docker/containers/679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec/hostname",
        "HostsPath": "/var/lib/docker/containers/679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec/hosts",
        "LogPath": "/var/lib/docker/containers/679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec/679f25c75b72f0b8019473acd86496a406cd757c9640d71a1256a3c0d30aa3ec-json.log",
        "Name": "/custom_no_tool-app-1",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "5000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "679f25c75b72",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOCKER_HOST=tcp://dind:2375",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.24",
                "PYTHON_SHA256=668391afabd5083faafa4543753d190f82f33ce6ba22d6e9ac728b43644b278a"
            ],
            "Cmd": [
                "python",
                "app.py"
            ],
            "Image": "custom_no_tool-app",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "3b09c9ea098ec9cb654d4cc4877ebdf4df4c0d5d350c010d83d7c985a46ea854",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "dind:service_started:false",
                "com.docker.compose.image": "sha256:a293164d4dbb941a5999d82a4489b51862c011a84bc92ff9f1ae94b01afc51b7",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-45232/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2021-45232/custom_no_tool",
                "com.docker.compose.service": "app",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-app-1",
                        "app"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "4d9dd4f33c1decd8c2257434436701f9f3a46e90b436515904b5c3ffa35b4d48",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-app-1",
                        "app",
                        "679f25c75b72"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:347fbf4c930e511cda2d1f91ae453e508db5f43f27550673fe94fcdd22c897e9",
            "size": 1622,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]