time="2025-10-30T02:57:57+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2018-18925/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 739B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 255B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 DONE 0.5s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 1.26kB done
#5 DONE 0.0s

#6 [1/5] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#6 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#6 DONE 0.0s

#7 [2/5] WORKDIR /app
#7 CACHED

#8 [3/5] COPY requirements.txt requirements.txt
#8 DONE 0.0s

#9 [4/5] RUN pip install --no-cache-dir -r requirements.txt
#9 1.581 Collecting Flask==1.0.2
#9 1.674   Downloading Flask-1.0.2-py2.py3-none-any.whl (91 kB)
#9 1.695      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 kB 4.6 MB/s eta 0:00:00
#9 1.759 Collecting Werkzeug==0.14.1
#9 1.778   Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322 kB)
#9 1.816      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.9/322.9 kB 8.8 MB/s eta 0:00:00
#9 1.859 Collecting Jinja2==2.11.3
#9 1.878   Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
#9 1.891      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.7/125.7 kB 12.5 MB/s eta 0:00:00
#9 2.058 Collecting markupsafe==2.0.1
#9 2.078   Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
#9 2.125 Collecting itsdangerous>=0.24
#9 2.148   Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 2.203 Collecting click>=5.1
#9 2.222   Downloading click-8.1.8-py3-none-any.whl (98 kB)
#9 2.229      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 22.1 MB/s eta 0:00:00
#9 2.315 Installing collected packages: Werkzeug, markupsafe, itsdangerous, click, Jinja2, Flask
#9 2.609 Successfully installed Flask-1.0.2 Jinja2-2.11.3 Werkzeug-0.14.1 click-8.1.8 itsdangerous-2.2.0 markupsafe-2.0.1
#9 2.609 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 2.736 
#9 2.736 [notice] A new release of pip is available: 23.0.1 -> 25.3
#9 2.736 [notice] To update, run: pip install --upgrade pip
#9 DONE 2.8s

#10 [5/5] COPY vulnerable_app.py vulnerable_app.py
#10 DONE 0.0s

#11 exporting to image
#11 exporting layers
#11 exporting layers 0.5s done
#11 exporting manifest sha256:9add7a60414f1be75b183ecafbe9916d0f527eda06ac252d84b8016c2c4b2236 0.0s done
#11 exporting config sha256:79be9e604d43008fb53ed972254e1bf3197afb3c50679213484f66cebfa33ee0 0.0s done
#11 exporting attestation manifest sha256:5540535839d2525de5dbadd010498da2c0d4f09c6f10dcf0432fef5f1ab575a7 0.0s done
#11 exporting manifest list sha256:9a95982836283a66c85c44bf254c77f5d0f0a82389e7b7813d31e8b9715b3fa5 done
#11 naming to docker.io/library/custom_no_tool-vulnerable_app:latest done
#11 unpacking to docker.io/library/custom_no_tool-vulnerable_app:latest
#11 unpacking to docker.io/library/custom_no_tool-vulnerable_app:latest 0.2s done
#11 DONE 0.8s

#12 resolving provenance for metadata file
#12 DONE 0.0s
 custom_no_tool-vulnerable_app  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container custom_no_tool-vulnerable_app-1  Creating
 Container custom_no_tool-vulnerable_app-1  Created
 Container custom_no_tool-vulnerable_app-1  Starting
 Container custom_no_tool-vulnerable_app-1  Started


sudo docker logs 8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)
 Traceback (most recent call last):
   File "/app/vulnerable_app.py", line 1, in <module>
     from flask import Flask, request, jsonify
   File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
     from .app import Flask, Request, Response
   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
     from . import cli, json
   File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
     from itsdangerous import json as _json
 ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)




sudo docker inspect 8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346[
    {
        "Id": "8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346",
        "Created": "2025-10-30T01:58:01.826926819Z",
        "Path": "python",
        "Args": [
            "vulnerable_app.py"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-30T01:58:31.311036326Z",
            "FinishedAt": "2025-10-30T01:58:31.855079432Z"
        },
        "Image": "sha256:9a95982836283a66c85c44bf254c77f5d0f0a82389e7b7813d31e8b9715b3fa5",
        "ResolvConfPath": "/var/lib/docker/containers/8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346/hostname",
        "HostsPath": "/var/lib/docker/containers/8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346/hosts",
        "LogPath": "/var/lib/docker/containers/8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346/8e279d7b45e7c2d4d81c854995d13ef0275dc421611d9c0dbd680402f3e5a346-json.log",
        "Name": "/custom_no_tool-vulnerable_app-1",
        "RestartCount": 9,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {
                "5000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "8e279d7b45e7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.24",
                "PYTHON_SHA256=668391afabd5083faafa4543753d190f82f33ce6ba22d6e9ac728b43644b278a"
            ],
            "Cmd": [
                "python",
                "vulnerable_app.py"
            ],
            "Image": "custom_no_tool-vulnerable_app",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "9091d471235cb348fef19383b0d65df9fcf6a415729a84240433dbcd29ba1793",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:9a95982836283a66c85c44bf254c77f5d0f0a82389e7b7813d31e8b9715b3fa5",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2018-18925/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2018-18925/custom_no_tool",
                "com.docker.compose.service": "vulnerable_app",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-vulnerable_app-1",
                        "vulnerable_app"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "595f96cff571b4652728d308291390262f05d49bc9ffb989251ce3a87da952a2",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-vulnerable_app-1",
                        "vulnerable_app",
                        "8e279d7b45e7"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:9add7a60414f1be75b183ecafbe9916d0f527eda06ac252d84b8016c2c4b2236",
            "size": 1810,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]