{
  "version": "15.0.6",
  "vulnerabilities": [
    {
      "id": "7bc3c0554713974464cc652e56c766fb2d799974afc4cd97bb1993c8e3645bcf",
      "category": "container_scanning",
      "message": "CVE-2005-2541 on debian/tar@1.35+dfsg-3.1",
      "description": "Tar 1.15.1 does not properly warn the user when extracting setuid or setgid files, which may allow local users or remote attackers to gain privileges.\n\n---\nThis is intended behaviour, after all tar is an archiving tool and you\nneed to give -p as a command line flag\n- tar <unfixed> (bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=328228; unimportant)",
      "cve": "CVE-2005-2541",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/tar@1.35%2Bdfsg-3.1?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "1.35+dfsg-3.1"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2005-2541",
          "value": "CVE-2005-2541",
          "url": "https://scout.docker.com/v/CVE-2005-2541?s=debian&n=tar&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1.35%2Bdfsg-3.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2005-2541?s=debian&n=tar&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1.35%2Bdfsg-3.1"
        }
      ]
    },
    {
      "id": "477dfe2fd942c106affe93660a8799d8d7deb2df4dd10f6fc012698e44ec894a",
      "category": "container_scanning",
      "message": "CVE-2007-5686 on debian/shadow@1:4.17.4-2",
      "description": "initscripts in rPath Linux 1 sets insecure permissions for the /var/log/btmp file, which allows local users to obtain sensitive information regarding authentication attempts.  NOTE: because sshd detects the insecure permissions and does not log certain events, this also prevents sshd from logging failed authentication attempts by remote attackers.\n\n---\n- shadow <unfixed> (unimportant)\nSee #290803, on Debian LOG_UNKFAIL_ENAB in login.defs is set to no so\nunknown usernames are not recorded on login failures",
      "cve": "CVE-2007-5686",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/shadow@1%3A4.17.4-2?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "1:4.17.4-2"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2007-5686",
          "value": "CVE-2007-5686",
          "url": "https://scout.docker.com/v/CVE-2007-5686?s=debian&n=shadow&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1%3A4.17.4-2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2007-5686?s=debian&n=shadow&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1%3A4.17.4-2"
        }
      ]
    },
    {
      "id": "bf1702ccc485752b28d0286515f37acc69737044b48327f2512fd502fec57685",
      "category": "container_scanning",
      "message": "CVE-2010-0928 on debian/openssl@3.5.1-1+deb13u1",
      "description": "OpenSSL 0.9.8i on the Gaisler Research LEON3 SoC on the Xilinx Virtex-II Pro FPGA uses a Fixed Width Exponentiation (FWE) algorithm for certain signature calculations, and does not verify the signature before providing it to a caller, which makes it easier for physically proximate attackers to determine the private key via a modified supply voltage for the microprocessor, related to a \"fault-based attack.\"\n\n---\nhttp://www.eecs.umich.edu/~valeria/research/publications/DATE10RSA.pdf\nhttps://github.com/openssl/openssl/discussions/24540\nFault injection based attacks are not within OpenSSLs threat model according\nto the security policy: https://www.openssl.org/policies/general/security-policy.html",
      "cve": "CVE-2010-0928",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/openssl@3.5.1-1%2Bdeb13u1?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "3.5.1-1+deb13u1"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2010-0928",
          "value": "CVE-2010-0928",
          "url": "https://scout.docker.com/v/CVE-2010-0928?s=debian&n=openssl&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.2.1-3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2010-0928?s=debian&n=openssl&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.2.1-3"
        }
      ]
    },
    {
      "id": "546e424966cb4404b271707714990282761fd71d8227ba4396991983aa84416f",
      "category": "container_scanning",
      "message": "CVE-2010-4756 on debian/glibc@2.41-12",
      "description": "The glob implementation in the GNU C Library (aka glibc or libc6) allows remote authenticated users to cause a denial of service (CPU and memory consumption) via crafted glob expressions that do not match any pathnames, as demonstrated by glob expressions in STAT commands to an FTP daemon, a different vulnerability than CVE-2010-2632.\n\n---\n- glibc <removed> (unimportant)\n- eglibc <unfixed> (unimportant)\nThat's standard POSIX behaviour implemented by (e)glibc. Applications using\nglob need to impose limits for themselves",
      "cve": "CVE-2010-4756",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2010-4756",
          "value": "CVE-2010-4756",
          "url": "https://scout.docker.com/v/CVE-2010-4756?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2010-4756?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "71d9a8edc9bacda13ab424364df04142766a4c9905e5354bee14423d4cf9e06a",
      "category": "container_scanning",
      "message": "CVE-2011-3374 on debian/apt@3.0.3",
      "description": "It was found that apt-key in apt, all versions, do not correctly validate gpg keys with the master keyring, leading to a potential man-in-the-middle attack.\n\n---\n- apt <unfixed> (unimportant; bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=642480)\nNot exploitable in Debian, since no keyring URI is defined",
      "cve": "CVE-2011-3374",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/apt@3.0.3?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "3.0.3"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2011-3374",
          "value": "CVE-2011-3374",
          "url": "https://scout.docker.com/v/CVE-2011-3374?s=debian&n=apt&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.0.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2011-3374?s=debian&n=apt&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.0.3"
        }
      ]
    },
    {
      "id": "586adb3dde9b0a3fe1b7d248f974f61396dbd59bdb024e9a7dbdab61cce45d05",
      "category": "container_scanning",
      "message": "CVE-2011-4116 on debian/perl@5.40.1-6",
      "description": "_is_safe in the File::Temp module for Perl does not properly handle symlinks.\n\n---\n- perl <unfixed> (unimportant; bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776268)\nhttp://thread.gmane.org/gmane.comp.security.oss.general/6174/focus=6177\nhttps://github.com/Perl-Toolchain-Gang/File-Temp/issues/14",
      "cve": "CVE-2011-4116",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/perl@5.40.1-6?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "5.40.1-6"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2011-4116",
          "value": "CVE-2011-4116",
          "url": "https://scout.docker.com/v/CVE-2011-4116?s=debian&n=perl&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D5.40.1-6"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2011-4116?s=debian&n=perl&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D5.40.1-6"
        }
      ]
    },
    {
      "id": "79cdf1ac50bd3273727ffede0159c296aa77d808f19b739d7ea8b5b522db5dd4",
      "category": "container_scanning",
      "message": "CVE-2013-4392 on debian/systemd@257.8-1~deb13u2",
      "description": "systemd, when updating file permissions, allows local users to change the permissions and SELinux security contexts for arbitrary files via a symlink attack on unspecified files.\n\n---\n- systemd <unfixed> (unimportant; bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=725357)\n[wheezy] - systemd <not-affected> (/etc/tmpfiles.d not supported in Wheezy)\nhttps://bugzilla.redhat.com/show_bug.cgi?id=859060\nonly relevant to systems running systemd along with selinux",
      "cve": "CVE-2013-4392",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/systemd@257.8-1~deb13u2?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "257.8-1~deb13u2"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2013-4392",
          "value": "CVE-2013-4392",
          "url": "https://scout.docker.com/v/CVE-2013-4392?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2013-4392?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ]
    },
    {
      "id": "7556d268935ce923c02edf29690c971f708621ef4f3935a7bd5aa244f1f1da60",
      "category": "container_scanning",
      "message": "CVE-2017-18018 on debian/coreutils@9.7-3",
      "description": "In GNU Coreutils through 8.29, chown-core.c in chown and chgrp does not prevent replacement of a plain file with a symlink during use of the POSIX \"-R -L\" options, which allows local users to modify the ownership of arbitrary files by leveraging a race condition.\n\n---\n- coreutils <unfixed> (unimportant)\nhttp://lists.gnu.org/archive/html/coreutils/2017-12/msg00045.html\nhttps://www.openwall.com/lists/oss-security/2018/01/04/3\nDocumentation patches proposed:\nhttps://lists.gnu.org/archive/html/coreutils/2017-12/msg00072.html\nhttps://lists.gnu.org/archive/html/coreutils/2017-12/msg00073.html\nNeutralised by kernel hardening",
      "cve": "CVE-2017-18018",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/coreutils@9.7-3?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "9.7-3"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2017-18018",
          "value": "CVE-2017-18018",
          "url": "https://scout.docker.com/v/CVE-2017-18018?s=debian&n=coreutils&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D9.7-3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2017-18018?s=debian&n=coreutils&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D9.7-3"
        }
      ]
    },
    {
      "id": "8d1af045dcfad2bfba7275523e3da2ecfaf567ebbfc8f1bb4209ba5d617a5248",
      "category": "container_scanning",
      "message": "CVE-2018-20796 on debian/glibc@2.41-12",
      "description": "In the GNU C Library (aka glibc or libc6) through 2.29, check_dst_limits_calc_pos_1 in posix/regexec.c has Uncontrolled Recursion, as demonstrated by '(\\227|)(\\\\1\\\\1|t1|\\\\\\2537)+' in grep.\n\n---\n- glibc <unfixed> (unimportant)\n- eglibc <removed> (unimportant)\nhttps://debbugs.gnu.org/cgi/bugreport.cgi?bug=34141\nhttps://lists.gnu.org/archive/html/bug-gnulib/2019-01/msg00108.html\nNo treated as vulnerability: https://sourceware.org/glibc/wiki/Security%20Exceptions",
      "cve": "CVE-2018-20796",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2018-20796",
          "value": "CVE-2018-20796",
          "url": "https://scout.docker.com/v/CVE-2018-20796?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2018-20796?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "3c0097819c4b42399b949b0e8ccc805118a189d4e697e028738fca7ddc3f31ad",
      "category": "container_scanning",
      "message": "CVE-2019-1010022 on debian/glibc@2.41-12",
      "description": "GNU Libc current is affected by: Mitigation bypass. The impact is: Attacker may bypass stack guard protection. The component is: nptl. The attack vector is: Exploit stack buffer overflow vulnerability and use this bypass vulnerability to bypass stack guard. NOTE: Upstream comments indicate \"this is being treated as a non-security bug and no real threat.\n\n---\n- glibc <unfixed> (unimportant)\nNot treated as a security issue by upstream\nhttps://sourceware.org/bugzilla/show_bug.cgi?id=22850",
      "cve": "CVE-2019-1010022",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-1010022",
          "value": "CVE-2019-1010022",
          "url": "https://scout.docker.com/v/CVE-2019-1010022?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-1010022?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "7632c671cf4bcb2d12d579faf64f118364cbf5595a336172cda0b6937fd2c469",
      "category": "container_scanning",
      "message": "CVE-2019-1010023 on debian/glibc@2.41-12",
      "description": "GNU Libc current is affected by: Re-mapping current loaded library with malicious ELF file. The impact is: In worst case attacker may evaluate privileges. The component is: libld. The attack vector is: Attacker sends 2 ELF files to victim and asks to run ldd on it. ldd execute code. NOTE: Upstream comments indicate \"this is being treated as a non-security bug and no real threat.\n\n---\n- glibc <unfixed> (unimportant)\nNot treated as a security issue by upstream\nhttps://sourceware.org/bugzilla/show_bug.cgi?id=22851",
      "cve": "CVE-2019-1010023",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-1010023",
          "value": "CVE-2019-1010023",
          "url": "https://scout.docker.com/v/CVE-2019-1010023?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-1010023?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "68900d7a26d06dd1b088707d8d7458e2dcd02741dcd5c6feebe9b177e625db55",
      "category": "container_scanning",
      "message": "CVE-2019-1010024 on debian/glibc@2.41-12",
      "description": "GNU Libc current is affected by: Mitigation bypass. The impact is: Attacker may bypass ASLR using cache of thread stack and heap. The component is: glibc. NOTE: Upstream comments indicate \"this is being treated as a non-security bug and no real threat.\n\n---\n- glibc <unfixed> (unimportant)\nNot treated as a security issue by upstream\nhttps://sourceware.org/bugzilla/show_bug.cgi?id=22852",
      "cve": "CVE-2019-1010024",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-1010024",
          "value": "CVE-2019-1010024",
          "url": "https://scout.docker.com/v/CVE-2019-1010024?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-1010024?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "839cbf1e4ceceb86c8cefc395f345819a394c628d567d098c204e528908cc932",
      "category": "container_scanning",
      "message": "CVE-2019-1010025 on debian/glibc@2.41-12",
      "description": "GNU Libc current is affected by: Mitigation bypass. The impact is: Attacker may guess the heap addresses of pthread_created thread. The component is: glibc. NOTE: the vendor's position is \"ASLR bypass itself is not a vulnerability.\n\n---\n- glibc <unfixed> (unimportant)\nNot treated as a security issue by upstream\nhttps://sourceware.org/bugzilla/show_bug.cgi?id=22853",
      "cve": "CVE-2019-1010025",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-1010025",
          "value": "CVE-2019-1010025",
          "url": "https://scout.docker.com/v/CVE-2019-1010025?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-1010025?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "870e1484799f459deaa735baab37772981e7b7600358b80986a4ebf1d6508497",
      "category": "container_scanning",
      "message": "CVE-2019-9192 on debian/glibc@2.41-12",
      "description": "In the GNU C Library (aka glibc or libc6) through 2.29, check_dst_limits_calc_pos_1 in posix/regexec.c has Uncontrolled Recursion, as demonstrated by '(|)(\\\\1\\\\1)*' in grep, a different issue than CVE-2018-20796. NOTE: the software maintainer disputes that this is a vulnerability because the behavior occurs only with a crafted pattern\n\n---\n- glibc <unfixed> (unimportant)\n- eglibc <removed> (unimportant)\nhttps://sourceware.org/bugzilla/show_bug.cgi?id=24269",
      "cve": "CVE-2019-9192",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/glibc@2.41-12?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-12"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2019-9192",
          "value": "CVE-2019-9192",
          "url": "https://scout.docker.com/v/CVE-2019-9192?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2019-9192?s=debian&n=glibc&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-12"
        }
      ]
    },
    {
      "id": "aae9b780e41c03779c012b5acc0b01d68080554c2c784da72ed31e87752c1036",
      "category": "container_scanning",
      "message": "CVE-2021-45346 on debian/sqlite3@3.46.1-7",
      "description": "A Memory Leak vulnerability exists in SQLite Project SQLite3 3.35.1 and 3.37.0 via maliciously crafted SQL Queries (made via editing the Database File), it is possible to query a record, and leak subsequent bytes of memory that extend beyond the record, which could let a malicious user obtain sensitive information. NOTE: The developer disputes this as a vulnerability stating that If you give SQLite a corrupted database file and submit a query against the database, it might read parts of the database that you did not intend or expect.\n\n---\n- sqlite3 <unfixed> (unimportant; bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005974)\n- sqlite <removed> (unimportant)\nhttps://github.com/guyinatuxedo/sqlite3_record_leaking\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2054793\nhttps://sqlite.org/forum/forumpost/056d557c2f8c452ed5bb9c215414c802b215ce437be82be047726e521342161e\nNegligible security impact",
      "cve": "CVE-2021-45346",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/sqlite3@3.46.1-7?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "3.46.1-7"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2021-45346",
          "value": "CVE-2021-45346",
          "url": "https://scout.docker.com/v/CVE-2021-45346?s=debian&n=sqlite3&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.46.1-7"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2021-45346?s=debian&n=sqlite3&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D3.46.1-7"
        }
      ]
    },
    {
      "id": "0cb1f888c35d9f7580e5fd3a7be464f133c6c94799cec431c56d81637d6c6eee",
      "category": "container_scanning",
      "message": "CVE-2022-0563 on debian/util-linux@2.41-5",
      "description": "A flaw was found in the util-linux chfn and chsh utilities when compiled with Readline support. The Readline library uses an \"INPUTRC\" environment variable to get a path to the library config file. When the library cannot parse the specified file, it prints an error message containing data from the file. This flaw allows an unprivileged user to read root-owned files, potentially leading to privilege escalation. This flaw affects util-linux versions prior to 2.37.4.\n\n---\n- util-linux <unfixed> (unimportant)\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2053151\nhttps://lore.kernel.org/util-linux/20220214110609.msiwlm457ngoic6w@ws.net.home/T/#u\nhttps://github.com/util-linux/util-linux/commit/faa5a3a83ad0cb5e2c303edbfd8cd823c9d94c17\nutil-linux in Debian does build with readline support but chfn and chsh are provided\nby src:shadow and util-linux is configured with --disable-chfn-chsh",
      "cve": "CVE-2022-0563",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/util-linux@2.41-5?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "2.41-5"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-0563",
          "value": "CVE-2022-0563",
          "url": "https://scout.docker.com/v/CVE-2022-0563?s=debian&n=util-linux&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-5"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-0563?s=debian&n=util-linux&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D2.41-5"
        }
      ]
    },
    {
      "id": "65bfa594f256ac1abeefdc90f0c56b1311710815ce885e9f950f1d3117d904cf",
      "category": "container_scanning",
      "message": "CVE-2023-31437 on debian/systemd@257.8-1~deb13u2",
      "description": "An issue was discovered in systemd 253. An attacker can modify a sealed log file such that, in some views, not all existing and sealed log messages are displayed. NOTE: the vendor reportedly sent \"a reply denying that any of the finding was a security vulnerability.\"\n\n---\n- systemd <unfixed> (unimportant)\nDisputed by upstream\nhttps://github.com/kastel-security/Journald/blob/main/journald-publication.pdf",
      "cve": "CVE-2023-31437",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/systemd@257.8-1~deb13u2?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "257.8-1~deb13u2"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-31437",
          "value": "CVE-2023-31437",
          "url": "https://scout.docker.com/v/CVE-2023-31437?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-31437?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ]
    },
    {
      "id": "a7b243d6ee21e05c79a81940cb46a4480abcdbdfadf092453fce4995470b5abf",
      "category": "container_scanning",
      "message": "CVE-2023-31438 on debian/systemd@257.8-1~deb13u2",
      "description": "An issue was discovered in systemd 253. An attacker can truncate a sealed log file and then resume log sealing such that checking the integrity shows no error, despite modifications. NOTE: the vendor reportedly sent \"a reply denying that any of the finding was a security vulnerability.\"\n\n---\n- systemd <unfixed> (unimportant)\nDisputed by upstream\nhttps://github.com/kastel-security/Journald/blob/main/journald-publication.pdf",
      "cve": "CVE-2023-31438",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/systemd@257.8-1~deb13u2?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "257.8-1~deb13u2"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-31438",
          "value": "CVE-2023-31438",
          "url": "https://scout.docker.com/v/CVE-2023-31438?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-31438?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ]
    },
    {
      "id": "b2aabf8043f6f91c683120f74a345a9556d36cc135b9c449e5ad9a24e11fcc8b",
      "category": "container_scanning",
      "message": "CVE-2023-31439 on debian/systemd@257.8-1~deb13u2",
      "description": "An issue was discovered in systemd 253. An attacker can modify the contents of past events in a sealed log file and then adjust the file such that checking the integrity shows no error, despite modifications. NOTE: the vendor reportedly sent \"a reply denying that any of the finding was a security vulnerability.\"\n\n---\n- systemd <unfixed> (unimportant)\nDisputed by upstream\nhttps://github.com/kastel-security/Journald/blob/main/journald-publication.pdf",
      "cve": "CVE-2023-31439",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/systemd@257.8-1~deb13u2?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "257.8-1~deb13u2"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-31439",
          "value": "CVE-2023-31439",
          "url": "https://scout.docker.com/v/CVE-2023-31439?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-31439?s=debian&n=systemd&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D257.8-1%7Edeb13u1"
        }
      ]
    },
    {
      "id": "c6835a3da4b9a4bf4a09df72fb07c3b28a342d4626cd34e646d932000e1e63ad",
      "category": "container_scanning",
      "message": "CVE-2025-5278 on debian/coreutils@9.7-3",
      "description": "A flaw was found in GNU Coreutils. The sort utility's begfield() function is vulnerable to a heap buffer under-read. The program may access memory outside the allocated buffer if a user runs a crafted command using the traditional key format. A malicious input could lead to a crash or leak sensitive data.\n\n---\n- coreutils <unfixed> (bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1106733; unimportant)\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2368764\nhttps://lists.gnu.org/archive/html/bug-coreutils/2025-05/msg00036.html\nhttps://lists.gnu.org/archive/html/bug-coreutils/2025-05/msg00040.html\nhttps://cgit.git.savannah.gnu.org/cgit/coreutils.git/commit/?id=8c9602e3a145e9596dc1a63c6ed67865814b6633\nhttps://www.openwall.com/lists/oss-security/2025/05/27/2\nhttps://debbugs.gnu.org/cgi/bugreport.cgi?bug=78507\nCrash in CLI tool, no security impact",
      "cve": "CVE-2025-5278",
      "severity": "Low",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/coreutils@9.7-3?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "9.7-3"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-5278",
          "value": "CVE-2025-5278",
          "url": "https://scout.docker.com/v/CVE-2025-5278?s=debian&n=coreutils&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D9.7-3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-5278?s=debian&n=coreutils&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D9.7-3"
        }
      ]
    },
    {
      "id": "dd2ebde146a603c0d714c3d809c81a2927287f2b540fb030ced910f30ef40133",
      "category": "container_scanning",
      "message": "CVE-2025-48432 on django@3.2.13",
      "description": "An issue was discovered in Django 5.2 before 5.2.2, 5.1 before 5.1.10, and 4.2 before 4.2.22. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.",
      "cve": "CVE-2025-48432",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 4.2.22",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-48432",
          "value": "CVE-2025-48432",
          "url": "https://scout.docker.com/v/CVE-2025-48432?s=github&n=django&t=pypi&vr=%3C4.2.22"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-48432?s=github&n=django&t=pypi&vr=%3C4.2.22"
        }
      ]
    },
    {
      "id": "78589da1cd8a32521f0034314d96d6ff6e53ee121f8a7f240fd15e181db207ed",
      "category": "container_scanning",
      "message": "CVE-2025-45582 on debian/tar@1.35+dfsg-3.1",
      "description": "GNU Tar through 1.35 allows file overwrite via directory traversal in crafted TAR archives, with a certain two-step process. First, the victim must extract an archive that contains a ../ symlink to a critical directory. Second, the victim must extract an archive that contains a critical file, specified via a relative pathname that begins with the symlink name and ends with that critical file's name. Here, the extraction follows the symlink and overwrites the critical file. This bypasses the protection mechanism of \"Member name contains '..'\" that would occur for a single TAR archive that attempted to specify the critical file via a ../ approach. For example, the first archive can contain \"x -> ../../../../../home/victim/.ssh\" and the second archive can contain x/authorized_keys. This can affect server applications that automatically extract any number of user-supplied TAR archives, and were relying on the blocking of traversal. This can also affect software installation processes in which \"tar xf\" is run more than once (e.g., when installing a package can automatically install two dependencies that are set up as untrusted tarballs instead of official packages).\n\n---\nDisputed tar issue, works as documented per upstream:\nhttps://lists.gnu.org/archive/html/bug-tar/2025-08/msg00012.html\nhttps://github.com/i900008/vulndb/blob/main/Gnu_tar_vuln.md",
      "cve": "CVE-2025-45582",
      "severity": "Medium",
      "confidence": "Unknown",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:deb/debian/tar@1.35%2Bdfsg-3.1?os_distro=trixie&os_name=debian&os_version=13"
          },
          "version": "1.35+dfsg-3.1"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-45582",
          "value": "CVE-2025-45582",
          "url": "https://scout.docker.com/v/CVE-2025-45582?s=debian&n=tar&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1.35%2Bdfsg-3.1"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-45582?s=debian&n=tar&ns=debian&t=deb&osn=debian&osv=13&vr=%3E%3D1.35%2Bdfsg-3.1"
        }
      ]
    },
    {
      "id": "2725ab7fb268835cad209665ecf2b9634c4b5c526f5c30587605c3d64327008a",
      "category": "container_scanning",
      "message": "CVE-2024-27351 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
      "cve": "CVE-2024-27351",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.25",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-27351",
          "value": "CVE-2024-27351",
          "url": "https://scout.docker.com/v/CVE-2024-27351?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.25"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-27351?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.25"
        }
      ]
    },
    {
      "id": "cbad38436234ddff822ed472295a3dd807a7d51c7078a2d27217bbcb91e14943",
      "category": "container_scanning",
      "message": "CVE-2025-8869 on pip@23.0.1",
      "description": "### Summary\n\nIn the fallback extraction path for source distributions, `pip` used Python’s `tarfile` module without verifying that symbolic/hard link targets resolve inside the intended extraction directory. A malicious sdist can include links that escape the target directory and overwrite arbitrary files on the invoking host during `pip install`.\n\n### Impact\n\nSuccessful exploitation enables arbitrary file overwrite outside the build/extraction directory on the machine running `pip`. This can be leveraged to tamper with configuration or startup files and may lead to further code execution depending on the environment, but the direct, guaranteed impact is integrity compromise on the vulnerable system.\n\n### Conditions\n\nThe issue is triggered when installing an attacker-controlled sdist (e.g., from an index or URL) and the fallback extraction code path is used. No special privileges are required beyond running `pip install`; active user action is necessary.\n\n### Remediation\n\nThe [fix](https://github.com/pypa/pip/pull/13550) is available starting in pip `25.3`. Using a Python interpreter that implements the safe-extraction behavior described by **PEP 706** provides additional defense in depth for other `tarfile` issues but is not a substitute for upgrading pip for this specific flaw.",
      "cve": "CVE-2025-8869",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade pip@23.0.1 to 25.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@23.0.1"
          },
          "version": "23.0.1"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-8869",
          "value": "CVE-2025-8869",
          "url": "https://scout.docker.com/v/CVE-2025-8869?s=github&n=pip&t=pypi&vr=%3C%3D25.2"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-8869?s=github&n=pip&t=pypi&vr=%3C%3D25.2"
        }
      ]
    },
    {
      "id": "3566e92d54b6aa1839cb682c4f530371bdb6f4e78c14cacc2af46ff90c961a9d",
      "category": "container_scanning",
      "message": "CVE-2024-45231 on django@3.2.13",
      "description": "An issue was discovered in Django v5.1.1, v5.0.9, and v4.2.16. The django.contrib.auth.forms.PasswordResetForm class, when used in a view implementing password reset flows, allows remote attackers to enumerate user e-mail addresses by sending password reset requests and observing the outcome (only when e-mail sending is consistently failing).",
      "cve": "CVE-2024-45231",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 4.2.16",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-45231",
          "value": "CVE-2024-45231",
          "url": "https://scout.docker.com/v/CVE-2024-45231?s=github&n=django&t=pypi&vr=%3C4.2.16"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-45231?s=github&n=django&t=pypi&vr=%3C4.2.16"
        }
      ]
    },
    {
      "id": "6762fe59162cfb810411b94bf246d8e1a9090acf954cb12f6dc2468159d89b61",
      "category": "container_scanning",
      "message": "CVE-2023-5752 on pip@23.0.1",
      "description": "When installing a package from a Mercurial VCS URL, e.g. `pip install hg+...`, with pip prior to v23.3, the specified Mercurial revision could be used to inject arbitrary configuration options to the `hg clone` call (e.g. `--config`). Controlling the Mercurial configuration can modify how and which repository is installed. This vulnerability does not affect users who aren't installing from Mercurial.",
      "cve": "CVE-2023-5752",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade pip@23.0.1 to 23.3",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/pip@23.0.1"
          },
          "version": "23.0.1"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-5752",
          "value": "CVE-2023-5752",
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-5752?s=github&n=pip&t=pypi&vr=%3C23.3"
        }
      ]
    },
    {
      "id": "735372c0dd462c694e5497141a4cd774c8a0e254046ce497762caa4bd086d067",
      "category": "container_scanning",
      "message": "CVE-2023-41164 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
      "cve": "CVE-2023-41164",
      "severity": "Medium",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.21",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-41164",
          "value": "CVE-2023-41164",
          "url": "https://scout.docker.com/v/CVE-2023-41164?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.21"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-41164?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.21"
        }
      ]
    },
    {
      "id": "58e9cf0509b636ace1534c9346eda250de166adeab8f5aaecce87e7c768ddee3",
      "category": "container_scanning",
      "message": "CVE-2025-57833 on django@3.2.13",
      "description": "An issue was discovered in Django 4.2 before 4.2.24, 5.1 before 5.1.12, and 5.2 before 5.2.6. FilteredRelation is subject to SQL injection in column aliases, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed QuerySet.annotate() or QuerySet.alias().",
      "cve": "CVE-2025-57833",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 4.2.24",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2025-57833",
          "value": "CVE-2025-57833",
          "url": "https://scout.docker.com/v/CVE-2025-57833?s=github&n=django&t=pypi&vr=%3C4.2.24"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2025-57833?s=github&n=django&t=pypi&vr=%3C4.2.24"
        }
      ]
    },
    {
      "id": "e2d49c083010a67dcef99a6ecfa0cf4825785371f30902e7cbdf2651db43dfea",
      "category": "container_scanning",
      "message": "CVE-2024-24680 on django@3.2.13",
      "description": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings.",
      "cve": "CVE-2024-24680",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.24",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2024-24680",
          "value": "CVE-2024-24680",
          "url": "https://scout.docker.com/v/CVE-2024-24680?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.24"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2024-24680?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.24"
        }
      ]
    },
    {
      "id": "76aac076130703d4bbe1e35a792366fb38a4727817b3feccad6dd4fc1522dca5",
      "category": "container_scanning",
      "message": "CVE-2022-41323 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression. ",
      "cve": "CVE-2022-41323",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.16",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-41323",
          "value": "CVE-2022-41323",
          "url": "https://scout.docker.com/v/CVE-2022-41323?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.16"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-41323?s=github&n=django&t=pypi&vr=%3E%3D3.2%2C%3C3.2.16"
        }
      ]
    },
    {
      "id": "a04edcb65e646f3570bf3b66ac0010aeec3f729e0a189a61535442b91b001633",
      "category": "container_scanning",
      "message": "CVE-2023-23969 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large.",
      "cve": "CVE-2023-23969",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.17",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-23969",
          "value": "CVE-2023-23969",
          "url": "https://scout.docker.com/v/CVE-2023-23969?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.17"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-23969?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.17"
        }
      ]
    },
    {
      "id": "c82e87ca9b2a3ad973230f81709957aaff3bdfec32dbb0e755b99859d1797464",
      "category": "container_scanning",
      "message": "CVE-2023-24580 on django@3.2.13",
      "description": "An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack.",
      "cve": "CVE-2023-24580",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.18",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-24580",
          "value": "CVE-2023-24580",
          "url": "https://scout.docker.com/v/CVE-2023-24580?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.18"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-24580?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.18"
        }
      ]
    },
    {
      "id": "d3af9f500d3d2cc4a194c9b5f4af067f70d7d857627233ebf521651f1416f81f",
      "category": "container_scanning",
      "message": "CVE-2023-36053 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, `EmailValidator` and `URLValidator` are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.",
      "cve": "CVE-2023-36053",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.20",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-36053",
          "value": "CVE-2023-36053",
          "url": "https://scout.docker.com/v/CVE-2023-36053?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.20"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-36053?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.20"
        }
      ]
    },
    {
      "id": "e189eb9b67fd56f7dada54241639bcd8bca9fc634482fee1ae4099b771e45adb",
      "category": "container_scanning",
      "message": "CVE-2023-43665 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.22, 4.1 before 4.1.12, and 4.2 before 4.2.6, the django.utils.text.Truncator chars() and words() methods (when used with html=True) are subject to a potential DoS (denial of service) attack via certain inputs with very long, potentially malformed HTML text. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which are thus also vulnerable. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232.",
      "cve": "CVE-2023-43665",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.22",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-43665",
          "value": "CVE-2023-43665",
          "url": "https://scout.docker.com/v/CVE-2023-43665?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.22"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-43665?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.22"
        }
      ]
    },
    {
      "id": "15e74107c5c026f7367bdc8639d6d44b8f391d799392f2b11eb83c2798de949f",
      "category": "container_scanning",
      "message": "CVE-2023-46695 on django@3.2.13",
      "description": "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
      "cve": "CVE-2023-46695",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.23",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-46695",
          "value": "CVE-2023-46695",
          "url": "https://scout.docker.com/v/CVE-2023-46695?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.23"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-46695?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.23"
        }
      ]
    },
    {
      "id": "1a94746e1f2d5088fc528084b95c55fe1d3f14c76e28ed1512b9e8a81588b753",
      "category": "container_scanning",
      "message": "CVE-2022-36359 on django@3.2.13",
      "description": "An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input.",
      "cve": "CVE-2022-36359",
      "severity": "High",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.15",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-36359",
          "value": "CVE-2022-36359",
          "url": "https://scout.docker.com/v/CVE-2022-36359?s=github&n=django&t=pypi&vr=%3C3.2.15"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-36359?s=github&n=django&t=pypi&vr=%3C3.2.15"
        }
      ]
    },
    {
      "id": "1691ea1162f387f8744adaca3edc997e57bcd4b42c036593cd04da4feef98771",
      "category": "container_scanning",
      "message": "CVE-2022-34265 on django@3.2.13",
      "description": "An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The `Trunc()` and `Extract()` database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected.",
      "cve": "CVE-2022-34265",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.14",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2022-34265",
          "value": "CVE-2022-34265",
          "url": "https://scout.docker.com/v/CVE-2022-34265?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.14"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2022-34265?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.14"
        }
      ]
    },
    {
      "id": "bba3a502523f59466584e55fcde492cd5c9449f235f87f4eb83e4a31775abc44",
      "category": "container_scanning",
      "message": "CVE-2023-31047 on django@3.2.13",
      "description": "In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django's \"Uploading multiple files\" documentation suggested otherwise.",
      "cve": "CVE-2023-31047",
      "severity": "Critical",
      "confidence": "Unknown",
      "solution": "Upgrade django@3.2.13 to 3.2.19",
      "scanner": {
        "id": "docker-scout",
        "name": "Docker Scout"
      },
      "location": {
        "dependency": {
          "package": {
            "name": "pkg:pypi/django@3.2.13"
          },
          "version": "3.2.13"
        },
        "operating_system": "debian 13",
        "image": "custom_no_tool-app:latest"
      },
      "identifiers": [
        {
          "type": "cve",
          "name": "CVE-2023-31047",
          "value": "CVE-2023-31047",
          "url": "https://scout.docker.com/v/CVE-2023-31047?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.19"
        }
      ],
      "links": [
        {
          "url": "https://scout.docker.com/v/CVE-2023-31047?s=github&n=django&t=pypi&vr=%3E%3D3.2a1%2C%3C3.2.19"
        }
      ]
    }
  ],
  "remediations": [],
  "scan": {
    "start_time": "2025-10-29T20:36:52",
    "end_time": "2025-10-29T20:36:52",
    "status": "success",
    "type": "container_scanning",
    "scanner": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    },
    "analyzer": {
      "id": "docker-scout",
      "name": "Docker Scout",
      "version": "1.18.3",
      "vendor": {
        "name": "Docker"
      }
    }
  }
}
