#1 [internal] load local bake definitions
#1 reading from stdin 1.44kB done
#1 DONE 0.0s

#2 [hardened-geoserver internal] load build definition from Dockerfile
#2 transferring dockerfile: 313B done
#2 DONE 0.0s

#3 [vulnerable-app internal] load build definition from Dockerfile
#3 transferring dockerfile: 392B done
#3 DONE 0.0s

#4 [vulnerable-app internal] load metadata for docker.io/library/python:3.10-slim
#4 ...

#5 [hardened-geoserver internal] load metadata for docker.io/osgeo/geoserver:2.25.2
#5 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

#4 [vulnerable-app internal] load metadata for docker.io/library/python:3.10-slim
#4 CANCELED
------
 > [hardened-geoserver internal] load metadata for docker.io/osgeo/geoserver:2.25.2:
------
Dockerfile:1

--------------------

   1 | >>> FROM osgeo/geoserver:2.25.2

   2 |     # Switch to root to install additional packages

   3 |     USER root

--------------------

target hardened-geoserver: failed to solve: osgeo/geoserver:2.25.2: failed to resolve source metadata for docker.io/osgeo/geoserver:2.25.2: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

