time="2025-10-29T19:53:22+01:00" level=warning msg="/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#1 [internal] load local bake definitions
#1 reading from stdin 775B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 119B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.9-slim
#3 DONE 0.4s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/4] FROM docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b
#5 resolve docker.io/library/python:3.9-slim@sha256:545badebace9a958b98d3e272f0f0d46c0a1a389ac77e24c33f2e7b548ce1b6b 0.0s done
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 32B done
#6 DONE 0.0s

#7 [3/4] COPY exploit.py .
#7 CACHED

#8 [2/4] WORKDIR /app
#8 CACHED

#9 [4/4] RUN pip install docker==4.4.4
#9 CACHED

#10 exporting to image
#10 exporting layers done
#10 exporting manifest sha256:69b9629ba41a01ee880329259a9654d865fbddea1bedbeb637ba78f6043fc6cc done
#10 exporting config sha256:7a6bce9940c6092319628bbbd98f77d98909e298756e4d08cb96c5265f26e605 done
#10 exporting attestation manifest sha256:556b3446b2c6430489193f60e3c66e33918ce04c05c0316ee5326fab6b52216c 0.0s done
#10 exporting manifest list sha256:4d5d22f684c70c758a27ce359f7f0da53e77bbb7c6d2f6a53499d55545e205ab 0.0s done
#10 naming to docker.io/library/custom_no_tool-attacker_client:latest
#10 naming to docker.io/library/custom_no_tool-attacker_client:latest done
#10 unpacking to docker.io/library/custom_no_tool-attacker_client:latest done
#10 DONE 0.1s

#11 resolving provenance for metadata file
#11 DONE 0.0s
 custom_no_tool-attacker_client  Built
 Network custom_no_tool_default  Creating
 Network custom_no_tool_default  Created
 Container custom_no_tool-vulnerable_docker-1  Creating
 Container custom_no_tool-vulnerable_docker-1  Created
 Container custom_no_tool-attacker_client-1  Creating
 Container custom_no_tool-attacker_client-1  Created
 Container custom_no_tool-vulnerable_docker-1  Starting
 Container custom_no_tool-vulnerable_docker-1  Started
 Container custom_no_tool-attacker_client-1  Starting
 Container custom_no_tool-attacker_client-1  Started


sudo docker logs 444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9 --details
STDOUT: 
STDERR:  Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn
     sock = connection.create_connection(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
   File "/usr/local/lib/python3.9/socket.py", line 966, in getaddrinfo
     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
 socket.gaierror: [Errno -2] Name or service not known
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
     response = self._make_request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 493, in _make_request
     conn.request(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 494, in request
     self.endheaders()
   File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
     self._send_output(message_body, encode_chunked=encode_chunked)
   File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
     self.send(msg)
   File "/usr/local/lib/python3.9/http/client.py", line 980, in send
     self.connect()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 325, in connect
     self.sock = self._new_conn()
   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in _new_conn
     raise NameResolutionError(self.host, self, e) from e
 urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7683c8f580d0>: Failed to resolve 'vulnerable_docker' ([Errno -2] Name or service not known)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 644, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 841, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 519, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='vulnerable_docker', port=2375): Max retries exceeded with url: /version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7683c8f580d0>: Failed to resolve 'vulnerable_docker' ([Errno -2] Name or service not known)"))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
     return self.version(api_version=False)["ApiVersion"]
   File "/usr/local/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
     return self._result(self._get(url), json=True)
   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
     return f(self, *args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 677, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPConnectionPool(host='vulnerable_docker', port=2375): Max retries exceeded with url: /version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7683c8f580d0>: Failed to resolve 'vulnerable_docker' ([Errno -2] Name or service not known)"))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/app/exploit.py", line 10, in <module>
     client = docker.from_env()
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
     return cls(
   File "/usr/local/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
     self.api = APIClient(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
     self._version = self._retrieve_server_version()
   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
     raise DockerException(
 docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='vulnerable_docker', port=2375): Max retries exceeded with url: /version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7683c8f580d0>: Failed to resolve 'vulnerable_docker' ([Errno -2] Name or service not known)"))




sudo docker inspect 444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9[
    {
        "Id": "444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9",
        "Created": "2025-10-29T18:53:23.823534519Z",
        "Path": "python",
        "Args": [
            "exploit.py"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2025-10-29T18:53:24.192729323Z",
            "FinishedAt": "2025-10-29T18:53:27.696840764Z"
        },
        "Image": "sha256:4d5d22f684c70c758a27ce359f7f0da53e77bbb7c6d2f6a53499d55545e205ab",
        "ResolvConfPath": "/var/lib/docker/containers/444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9/hostname",
        "HostsPath": "/var/lib/docker/containers/444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9/hosts",
        "LogPath": "/var/lib/docker/containers/444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9/444d13bdc9e641769bd7bdb8b2d5202a78315c8e20b347706dcc874aefbd15e9-json.log",
        "Name": "/custom_no_tool-attacker_client-1",
        "RestartCount": 0,
        "Driver": "overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "custom_no_tool_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/interrupts",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "overlayfs"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "444d13bdc9e6",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOCKER_HOST=tcp://vulnerable_docker:2375",
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.9.24",
                "PYTHON_SHA256=668391afabd5083faafa4543753d190f82f33ce6ba22d6e9ac728b43644b278a"
            ],
            "Cmd": [
                "python",
                "exploit.py"
            ],
            "Image": "custom_no_tool-attacker_client",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "4d990fbcefbfb102317b97de90b487741c76b49904905c502607a2049339b369",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "vulnerable_docker:service_started:false",
                "com.docker.compose.image": "sha256:4d5d22f684c70c758a27ce359f7f0da53e77bbb7c6d2f6a53499d55545e205ab",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "custom_no_tool",
                "com.docker.compose.project.config_files": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/gabriele/thesis-project/Agents-for-Vulnerable-Dockers-and-related-Benchmarks/dockers/CVE-2019-14234/custom_no_tool",
                "com.docker.compose.service": "attacker_client",
                "com.docker.compose.version": "2.40.2",
                "desktop.docker.io/wsl-distro": "Ubuntu"
            },
            "StopTimeout": 1
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "SandboxKey": "",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "custom_no_tool_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "custom_no_tool-attacker_client-1",
                        "attacker_client"
                    ],
                    "MacAddress": "",
                    "DriverOpts": null,
                    "GwPriority": 0,
                    "NetworkID": "9aa9e9a327313956a833809e4a6174c5b8d93e55cb147062f9eae30a5744d6c6",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "custom_no_tool-attacker_client-1",
                        "attacker_client",
                        "444d13bdc9e6"
                    ]
                }
            }
        },
        "ImageManifestDescriptor": {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:69b9629ba41a01ee880329259a9654d865fbddea1bedbeb637ba78f6043fc6cc",
            "size": 1622,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    }
]